/* Determ C99-native SHA-3 / SHAKE (NIST FIPS 202), built on Keccak-f[1600].
 *
 * The extendable-output functions SHAKE128 / SHAKE256 are the eXtendable-Output
 * Function (XOF) prerequisite for the post-quantum signature track: ML-DSA
 * (Dilithium, FIPS 204) uses SHAKE128 for public-matrix expansion and SHAKE256
 * for secret/masking sampling and the message hash; SLH-DSA (FIPS 205) uses
 * SHAKE256 throughout. This module ships the XOF first, KAT-verified, so those
 * schemes build on a validated sponge. The fixed-length SHA3-256 / SHA3-512 fall
 * out of the same permutation and are independently useful.
 *
 * Validated by `determ test-sha3-c99`: FIPS 202 known-answer vectors plus the
 * `tools/vectors/sha3_shake.json` corpus cross-generated by Python `hashlib`
 * (sha3_256 / sha3_512 / shake_128 / shake_256 — an independent implementation),
 * covering the sponge rate boundaries (input length rate-1 / rate / rate+1),
 * multi-block inputs, and SHAKE output lengths exceeding the rate (forcing a
 * squeeze-permute). Incremental (absorb/squeeze) == one-shot.
 *
 * Keccak is data-independent by construction — the permutation has no
 * secret-dependent branch, rotation, or memory index (no S-box table), so it is
 * naturally constant-time. State is little-endian lane-packed via explicit
 * shifts (no uint64<->uint8 aliasing), so the output is byte-identical across
 * toolchains/endianness (the repo's cross-toolchain determinism discipline).
 */
#ifndef DETERM_CRYPTO_SHA3_H
#define DETERM_CRYPTO_SHA3_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Sponge rates (bytes) = (1600 - 2*capacity)/8. */
#define DETERM_SHA3_256_RATE  136u   /* capacity 512 */
#define DETERM_SHA3_512_RATE   72u   /* capacity 1024 */
#define DETERM_SHAKE128_RATE  168u   /* capacity 256 */
#define DETERM_SHAKE256_RATE  136u   /* capacity 512 */

/* Domain-separation / pad-start bytes (pad10*1, FIPS 202 §B.2). */
#define DETERM_SHA3_DOMAIN   0x06u
#define DETERM_SHAKE_DOMAIN  0x1Fu

/* Incremental Keccak sponge context (absorb then squeeze). Usable directly for
 * SHAKE streaming (ML-DSA rejection sampling squeezes in blocks); the one-shot
 * functions below are thin wrappers. */
typedef struct {
    uint64_t s[25];    /* state: 25 little-endian 64-bit lanes */
    size_t   rate;     /* block size in bytes */
    size_t   pos;      /* byte offset within the current block */
    uint8_t  dsbyte;   /* domain-separation pad-start byte */
    uint8_t  squeezing;/* 0 = absorbing, 1 = squeezing */
} determ_keccak_ctx;

/* Initialize a sponge with an explicit rate + domain byte. */
void determ_keccak_init(determ_keccak_ctx* ctx, size_t rate, uint8_t dsbyte);
/* Absorb input (may be called repeatedly before the first squeeze). */
void determ_keccak_absorb(determ_keccak_ctx* ctx, const uint8_t* in, size_t inlen);
/* Apply the pad and transition to squeezing (idempotent — auto-called by squeeze). */
void determ_keccak_finalize(determ_keccak_ctx* ctx);
/* Squeeze output (may be called repeatedly for a running XOF stream). */
void determ_keccak_squeeze(determ_keccak_ctx* ctx, uint8_t* out, size_t outlen);

/* Convenience initializers. */
void determ_shake128_init(determ_keccak_ctx* ctx);
void determ_shake256_init(determ_keccak_ctx* ctx);

/* One-shot fixed-length digests. */
void determ_sha3_256(uint8_t out[32], const uint8_t* in, size_t inlen);
void determ_sha3_512(uint8_t out[64], const uint8_t* in, size_t inlen);

/* One-shot XOFs: write `outlen` bytes to `out`. */
void determ_shake128(uint8_t* out, size_t outlen, const uint8_t* in, size_t inlen);
void determ_shake256(uint8_t* out, size_t outlen, const uint8_t* in, size_t inlen);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* DETERM_CRYPTO_SHA3_H */
