/* Determ C99-native Argon2id (RFC 9106 / P-H-C reference) — the memory-hard
 * password hash, libsodium-free (CRYPTO-C99-SPEC §3.6). Built on the C99 BLAKE2b
 * (src/crypto/blake2/). The intended consumer is the passphrase-encrypted keyfile
 * KDF (today libsodium crypto_pwhash); this is the drop-in replacement.
 *
 * Explicit-parameter (raw) interface, matching the P-H-C `argon2id_hash_raw`:
 * libsodium's crypto_pwhash_argon2id maps (opslimit, memlimit) -> (t_cost=opslimit,
 * m_cost=memlimit/1024, parallelism=1, version=0x13), so determ_argon2id(t, m, 1,
 * ...) is validated byte-equal vs crypto_pwhash_argon2id(opslimit=t, memlimit=m*1024)
 * by `determ-wallet test-argon2id-c99` (the only AEAD-grade oracle is libsodium,
 * which the determ daemon does not link — so the cross-validation lives in the
 * libsodium-linked wallet binary).
 *
 * NOTE: memory-hard, so NOT constant-time in the data-dependent passes by design
 * (that is Argon2d's GPU-resistance). The Argon2id hybrid keeps the first half of
 * the first pass (pass 0, slices 0..SYNC_POINTS/2-1 per RFC 9106 §3.4) data-
 * INdependent, with the reference-block addressing generated by BLAKE2b over PUBLIC
 * parameters only (a zero block + {pass, lane, slice, mem, t_cost, type} — never the
 * password). The remaining slices/passes are data-DEPENDENT: their memory-access
 * pattern is a function of the password, so an attacker with cache/power side-channel
 * measurement could in principle learn information about it during those phases. This
 * is intentional (the Argon2d component's GPU resistance); the hybrid only guarantees
 * the *initial* addressing is secret-independent. Threat model: the host running the
 * KDF is trusted against fine-grained microarchitectural side channels. Inputs flow
 * through BLAKE2b; the block memory is determ_secure_zero'd before free.
 */
#ifndef DETERM_CRYPTO_ARGON2ID_H
#define DETERM_CRYPTO_ARGON2ID_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Argon2id v1.3. Writes `outlen` bytes (>= 4) to `out`. `t_cost` >= 1 passes,
 * `m_cost` >= 8*parallelism KiB, `parallelism` >= 1. `pwd`/`salt` may be NULL when
 * their length is 0 (salt should be >= 8 bytes per the spec; libsodium uses 16).
 * Returns 0 on success, -1 on a bad parameter or a memory-allocation failure. */
int determ_argon2id(uint8_t *out, size_t outlen,
                    const uint8_t *pwd, size_t pwdlen,
                    const uint8_t *salt, size_t saltlen,
                    uint32_t t_cost, uint32_t m_cost, uint32_t parallelism);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* DETERM_CRYPTO_ARGON2ID_H */
