/* `determ-dsso selftest-pid` — the falsify-on-mutant gate for DSSO's
 * wallet-relying-party surface.
 *
 * WHAT THIS GATE ASSERTS, AND WHERE. Each of the nine verification rules of
 * dsso_pid.h gets an ACCEPT case and its own rejections, asserted against the
 * status code that rule returns — so removing exactly one check turns exactly
 * its own arms RED and leaves the rest green. The account-binding rules of
 * dsso_bind.h get the same treatment. Below those, the three readers that face
 * a hostile wallet (base64url, JSON, inflate) are asserted directly rather than
 * through the pipeline, because a gate on a proxy is worthless: a parser bug is
 * a parser assertion.
 *
 * THE FIXTURES are generated by an INDEPENDENT implementation (see the header
 * of dsso_pid_vectors.h) — pure-Python P-256 anchored to the RFC 6979 A.2.5
 * known-answer vectors and cross-checked against OpenSSL. In addition, the
 * ES256 verifier under test is anchored to those SAME published vectors
 * directly, in this file, so the crypto leg does not depend on the generator at
 * all.
 *
 * THE FUZZ ARMS mutate the readers' inputs thousands of times. The property is
 * a DEFINITE VERDICT WITHOUT A CRASH: every mutant either parses (and then the
 * accessors walk it without disturbing the canaries around the buffer) or is
 * rejected with a negative status. For the presentation itself the property is
 * stronger — any mutant that differs from the original byte string must be
 * REJECTED, because every byte of a presentation is covered by one of the two
 * signatures or by the sd_hash. */
#include <stdio.h>
#include <string.h>

#include "dsso.h"
#include "dsso_jose.h"
#include "dsso_pid.h"
#include "dsso_bind.h"
#include "dsso_pid_vectors.h"

#include "determ/crypto/sha2/sha2.h"

static int g_fail;
static int g_checks;

#define CHECK(cond, msg) do {                                  \
        g_checks++;                                            \
        if (cond) printf("  PASS: %s\n", (msg));               \
        else { printf("  FAIL: %s\n", (msg)); g_fail++; }      \
    } while (0)

static dsso_slice S(const char *s) { dsso_slice v; v.p = (const uint8_t *)s; v.n = strlen(s); return v; }
static dsso_slice SB(const uint8_t *p, size_t n) { dsso_slice v; v.p = p; v.n = n; return v; }

/* ── the injected status-token fetch, driven from fixtures ────────────────── */
static int fixture_fetch(void *ctx, const uint8_t *uri, size_t uri_len,
                         uint8_t *out, size_t cap, size_t *outlen) {
    size_t i;
    (void)ctx;
    for (i = 0; i < PIDV_N_STATUS; ++i) {
        size_t n = strlen(PIDV_STATUS_FIXTURES[i].uri);
        if (n != uri_len || memcmp(PIDV_STATUS_FIXTURES[i].uri, uri, n) != 0) continue;
        if (PIDV_STATUS_FIXTURES[i].fail) return -1;      /* unreachable list */
        n = strlen(PIDV_STATUS_FIXTURES[i].token);
        if (n > cap) return -1;
        memcpy(out, PIDV_STATUS_FIXTURES[i].token, n);
        *outlen = n;
        return 0;
    }
    return -1;
}

static dsso_trust_anchor g_anchors[3];
static dsso_trust_list   g_trust;

static void trust_init(void) {
    memset(g_anchors, 0, sizeof g_anchors);
    g_anchors[0].iss = PIDV_ISS;  g_anchors[0].kid = PIDV_KID;
    memcpy(g_anchors[0].pk, PIDV_PK_ISSUER, 65);
    g_anchors[0].max_loa = DSSO_LOA_HIGH;
    /* A second PID Provider whose anchor entry caps it at SUBSTANTIAL, so the
     * "a token cannot talk its issuer up" rule has something to bite on. */
    g_anchors[1].iss = PIDV_ISS2; g_anchors[1].kid = PIDV_KID2;
    memcpy(g_anchors[1].pk, PIDV_PK_ISSUER2, 65);
    g_anchors[1].max_loa = DSSO_LOA_SUBSTANTIAL;
    /* The status-list signer: same issuer, its own key id. */
    g_anchors[2].iss = PIDV_ISS;  g_anchors[2].kid = PIDV_KID_STATUS;
    memcpy(g_anchors[2].pk, PIDV_PK_STATUS, 65);
    g_anchors[2].max_loa = DSSO_LOA_HIGH;
    g_trust.a = g_anchors;
    g_trust.n = 3;
}

static dsso_pid_policy pol_with(const char *nonce) {
    dsso_pid_policy p;
    memset(&p, 0, sizeof p);
    p.rp_id        = PIDV_RP_ID;
    p.nonce        = (const uint8_t *)nonce;
    p.nonce_len    = strlen(nonce);
    p.now          = PIDV_NOW;
    p.max_skew     = 120;
    p.max_pres_age = 300;
    p.max_cred_age = 86400 * 365;
    p.required_loa = DSSO_LOA_HIGH;
    p.trust        = &g_trust;
    p.fetch        = fixture_fetch;
    p.fetch_ctx    = NULL;
    return p;
}

/* ── deterministic PRNG for the fuzz arms (xorshift64*, fixed seed) ───────── */
static uint64_t g_rng = 0x9E3779B97F4A7C15ull;
static uint64_t rnd(void) {
    g_rng ^= g_rng >> 12; g_rng ^= g_rng << 25; g_rng ^= g_rng >> 27;
    return g_rng * 0x2545F4914F6CDD1Dull;
}
static size_t rnd_below(size_t n) { return n ? (size_t)(rnd() % (uint64_t)n) : 0; }

/* ── RFC 6979 A.2.5 (P-256 / SHA-256) — the C verifier's external anchor ──── */
static const uint8_t KAT_PK[65] = {
    0x04,
    0x60,0xFE,0xD4,0xBA,0x25,0x5A,0x9D,0x31,0xC9,0x61,0xEB,0x74,0xC6,0x35,0x6D,0x68,
    0xC0,0x49,0xB8,0x92,0x3B,0x61,0xFA,0x6C,0xE6,0x69,0x62,0x2E,0x60,0xF2,0x9F,0xB6,
    0x79,0x03,0xFE,0x10,0x08,0xB8,0xBC,0x99,0xA4,0x1A,0xE9,0xE9,0x56,0x28,0xBC,0x64,
    0xF2,0xF1,0xB2,0x0C,0x2D,0x7E,0x9F,0x51,0x77,0xA3,0xC2,0x94,0xD4,0x46,0x22,0x99
};
static const uint8_t KAT_SIG_SAMPLE[64] = {
    0xEF,0xD4,0x8B,0x2A,0xAC,0xB6,0xA8,0xFD,0x11,0x40,0xDD,0x9C,0xD4,0x5E,0x81,0xD6,
    0x9D,0x2C,0x87,0x7B,0x56,0xAA,0xF9,0x91,0xC3,0x4D,0x0E,0xA8,0x4E,0xAF,0x37,0x16,
    0xF7,0xCB,0x1C,0x94,0x2D,0x65,0x7C,0x41,0xD4,0x36,0xC7,0xA1,0xB6,0xE2,0x9F,0x65,
    0xF3,0xE9,0x00,0xDB,0xB9,0xAF,0xF4,0x06,0x4D,0xC4,0xAB,0x2F,0x84,0x3A,0xCD,0xA8
};
static const uint8_t KAT_SIG_TEST[64] = {
    0xF1,0xAB,0xB0,0x23,0x51,0x83,0x51,0xCD,0x71,0xD8,0x81,0x56,0x7B,0x1E,0xA6,0x63,
    0xED,0x3E,0xFC,0xF6,0xC5,0x13,0x2B,0x35,0x4F,0x28,0xD3,0xB0,0xB7,0xD3,0x83,0x67,
    0x01,0x9F,0x41,0x13,0x74,0x2A,0x2B,0x14,0xBD,0x25,0x92,0x6B,0x49,0xC6,0x49,0x15,
    0x5F,0x26,0x7E,0x60,0xD3,0x81,0x4B,0x4C,0x0C,0xC8,0x42,0x50,0xE4,0x6F,0x00,0x83
};

/* ── section 1: the bounded base64url decoder ─────────────────────────────── */
static void test_b64url(void) {
    uint8_t out[64];
    size_t n = 0;
    printf("\n-- base64url (RFC 4648 §5, unpadded; strict + canonical) --\n");
    CHECK(dsso_b64url_decode(S("QQ"), out, sizeof out, &n) == DSSO_OK && n == 1 && out[0] == 'A',
          "b64url: a two-character group decodes to one byte");
    CHECK(dsso_b64url_decode(S("QUJD"), out, sizeof out, &n) == DSSO_OK && n == 3 &&
          !memcmp(out, "ABC", 3),
          "b64url: a full group decodes to three bytes");
    CHECK(dsso_b64url_decode(S("QR"), out, sizeof out, &n) == DSSO_E_FORMAT,
          "b64url: a NON-CANONICAL tail (unused bits set) is rejected");
    CHECK(dsso_b64url_decode(S("QUJ="), out, sizeof out, &n) == DSSO_E_FORMAT,
          "b64url: '=' padding is rejected (JOSE is unpadded)");
    CHECK(dsso_b64url_decode(S("QQ+/"), out, sizeof out, &n) == DSSO_E_FORMAT,
          "b64url: the standard alphabet's '+' and '/' are rejected");
    CHECK(dsso_b64url_decode(S("Q"), out, sizeof out, &n) == DSSO_E_FORMAT,
          "b64url: a length of 1 mod 4 encodes nothing and is rejected");
    CHECK(dsso_b64url_decode(S("QQ QQ"), out, sizeof out, &n) == DSSO_E_FORMAT,
          "b64url: embedded whitespace is rejected");
    CHECK(dsso_b64url_decode(S("QUJDRA"), out, 2, &n) == DSSO_E_ARG,
          "b64url: an output that would exceed the cap is refused, not truncated");
    out[0] = 0xAA;
    CHECK(dsso_b64url_decode(S("QR"), out, sizeof out, &n) == DSSO_E_FORMAT && out[0] == 0xAA,
          "b64url: the output buffer is untouched on failure");
    CHECK(dsso_b64url_decode(S(""), out, sizeof out, &n) == DSSO_OK && n == 0,
          "b64url: an empty input decodes to zero bytes");
}

/* ── section 2: the bounded JSON reader ───────────────────────────────────── */
static const char FUZZ_JSON[] =
    "{\"iss\":\"https://pid.example\",\"n\":[1,2,{\"b\":null}],"
    "\"e\":\"\\u00e9\\ud83d\\ude00\",\"d\":-12.5e3,\"t\":true}";

static void test_json(void) {
    dsso_slice root, v;
    dsso_json_type t;
    int64_t i64;
    uint8_t buf[64];
    size_t n = 0, cnt = 0;

    printf("\n-- bounded JSON reader (RFC 8259 subset, strict) --\n");
    CHECK(dsso_json_validate(S(FUZZ_JSON), &root, &t) == DSSO_OK && t == DSSO_JSON_OBJECT,
          "json: a well-formed document validates as an object");
    CHECK(dsso_json_member(root, "iss", &v, &t) == DSSO_OK && t == DSSO_JSON_STRING &&
          dsso_json_string_equals(v, "https://pid.example"),
          "json: a string member is found and compares by VALUE");
    CHECK(dsso_json_member(root, "n", &v, &t) == DSSO_OK && t == DSSO_JSON_ARRAY &&
          dsso_json_array_len(v, &cnt) == DSSO_OK && cnt == 3,
          "json: an array member reports its element count");
    CHECK(dsso_json_member(root, "e", &v, &t) == DSSO_OK &&
          dsso_json_string(v, buf, sizeof buf, &n) == DSSO_OK && n == 2 + 4,
          "json: \\u escapes and a surrogate pair decode to UTF-8");
    CHECK(dsso_json_member(root, "d", &v, &t) == DSSO_OK && t == DSSO_JSON_NUMBER &&
          dsso_json_int(v, &i64) == DSSO_E_FORMAT,
          "json: a non-integer number is refused where an integer is required");
    CHECK(dsso_json_member(root, "absent", &v, &t) == DSSO_E_FORMAT,
          "json: an absent member is a failure, never a zero value");

    CHECK(dsso_json_validate(S("{\"a\":1,\"a\":2}"), &root, &t) == DSSO_E_FORMAT,
          "json: a DUPLICATE member name is rejected, not resolved");
    CHECK(dsso_json_validate(S("{\"a\":1,\"\\u0061\":2}"), &root, &t) == DSSO_E_FORMAT,
          "json: a duplicate hidden behind a \\u escape is still a duplicate");
    CHECK(dsso_json_validate(S("{\"a\":1} trailing"), &root, &t) == DSSO_E_FORMAT,
          "json: trailing data after the top-level value is rejected");
    CHECK(dsso_json_validate(S("{\"a\":1}{\"b\":2}"), &root, &t) == DSSO_E_FORMAT,
          "json: a second top-level value is trailing data");
    CHECK(dsso_json_validate(S("[[[[[[[[[[1]]]]]]]]]]"), &root, &t) == DSSO_E_FORMAT,
          "json: nesting past the fixed depth cap is rejected");
    CHECK(dsso_json_validate(S("[[[[1]]]]"), &root, &t) == DSSO_OK,
          "json: nesting within the depth cap is accepted");
    CHECK(dsso_json_validate(S("{\"a\":01}"), &root, &t) == DSSO_E_FORMAT,
          "json: a leading zero is not an RFC 8259 number");
    CHECK(dsso_json_validate(S("{\"a\":+1}"), &root, &t) == DSSO_E_FORMAT,
          "json: a leading '+' is not an RFC 8259 number");
    CHECK(dsso_json_validate(S("{\"a\":NaN}"), &root, &t) == DSSO_E_FORMAT,
          "json: NaN / Infinity are rejected");
    CHECK(dsso_json_validate(S("{\"a\":\"x\ty\"}"), &root, &t) == DSSO_E_FORMAT,
          "json: a raw control character inside a string is rejected");
    CHECK(dsso_json_validate(S("{\"a\":\"\\q\"}"), &root, &t) == DSSO_E_FORMAT,
          "json: an unknown escape is rejected");
    CHECK(dsso_json_validate(S("{\"a\":\"\\ud83d\"}"), &root, &t) == DSSO_E_FORMAT,
          "json: an unpaired surrogate is rejected");
    CHECK(dsso_json_validate(S("{\"a\":1,}"), &root, &t) == DSSO_E_FORMAT,
          "json: a trailing comma is rejected");
    CHECK(dsso_json_validate(S("{'a':1}"), &root, &t) == DSSO_E_FORMAT,
          "json: single-quoted names are rejected");
    CHECK(dsso_json_validate(S("{\"a\":1 /*c*/}"), &root, &t) == DSSO_E_FORMAT,
          "json: comments are rejected");
    {
        /* One element past DSSO_JSON_MAX_ELEMS. */
        static char big[DSSO_JSON_MAX_ELEMS * 2 + 8];
        size_t k, o = 0;
        big[o++] = '[';
        for (k = 0; k <= DSSO_JSON_MAX_ELEMS; ++k) { big[o++] = '1'; big[o++] = ','; }
        big[o - 1] = ']';
        CHECK(dsso_json_validate(SB((const uint8_t *)big, o), &root, &t) == DSSO_E_FORMAT,
              "json: a container past the element cap is rejected");
    }
    CHECK(dsso_json_validate(S("{\"a\":9223372036854775808}"), &root, &t) == DSSO_OK &&
          dsso_json_member(root, "a", &v, &t) == DSSO_OK &&
          dsso_json_int(v, &i64) == DSSO_E_FORMAT,
          "json: an integer past int64 range is refused rather than wrapped");
}

/* ── section 3: ES256 over P-256, composed on the shipped stack ───────────── */
static void test_es256(void) {
    uint8_t sig[64], pk[65];
    printf("\n-- ES256 (RFC 7515 §3.4) on determ::c99 P-256 --\n");
    CHECK(dsso_es256_verify(KAT_PK, S("sample"), KAT_SIG_SAMPLE) == DSSO_OK,
          "es256: RFC 6979 A.2.5 'sample' KAT verifies (external anchor)");
    CHECK(dsso_es256_verify(KAT_PK, S("test"), KAT_SIG_TEST) == DSSO_OK,
          "es256: RFC 6979 A.2.5 'test' KAT verifies (external anchor)");
    CHECK(dsso_es256_verify(KAT_PK, S("sampla"), KAT_SIG_SAMPLE) == DSSO_E_CRYPTO,
          "es256: a one-byte change to the message is rejected");
    memcpy(sig, KAT_SIG_SAMPLE, 64); sig[63] ^= 1;
    CHECK(dsso_es256_verify(KAT_PK, S("sample"), sig) == DSSO_E_CRYPTO,
          "es256: a one-bit change to s is rejected");
    memcpy(sig, KAT_SIG_SAMPLE, 64); sig[0] ^= 1;
    CHECK(dsso_es256_verify(KAT_PK, S("sample"), sig) == DSSO_E_CRYPTO,
          "es256: a one-bit change to r is rejected");
    memset(sig, 0, 64); memcpy(sig + 32, KAT_SIG_SAMPLE + 32, 32);
    CHECK(dsso_es256_verify(KAT_PK, S("sample"), sig) == DSSO_E_FORMAT,
          "es256: r == 0 is a non-canonical scalar, rejected before any arithmetic");
    memcpy(sig, KAT_SIG_SAMPLE, 64); memset(sig + 32, 0, 32);
    CHECK(dsso_es256_verify(KAT_PK, S("sample"), sig) == DSSO_E_FORMAT,
          "es256: s == 0 is a non-canonical scalar");
    memcpy(sig, KAT_SIG_SAMPLE, 64); memset(sig, 0xFF, 32);
    CHECK(dsso_es256_verify(KAT_PK, S("sample"), sig) == DSSO_E_FORMAT,
          "es256: r >= n is a non-canonical scalar");
    memcpy(sig, KAT_SIG_SAMPLE, 64); memset(sig + 32, 0xFF, 32);
    CHECK(dsso_es256_verify(KAT_PK, S("sample"), sig) == DSSO_E_FORMAT,
          "es256: s >= n is a non-canonical scalar");
    memcpy(pk, KAT_PK, 65); pk[64] ^= 1;
    CHECK(dsso_es256_verify(pk, S("sample"), KAT_SIG_SAMPLE) == DSSO_E_CRYPTO,
          "es256: an off-curve public key is rejected, never used");
    memcpy(pk, KAT_PK, 65); pk[0] = 0x02;
    CHECK(dsso_es256_verify(pk, S("sample"), KAT_SIG_SAMPLE) == DSSO_E_CRYPTO,
          "es256: a non-SEC1-uncompressed key encoding is rejected");
}

/* ── section 4: the bounded inflate ───────────────────────────────────────── */
static void test_inflate(void) {
    uint8_t out[DSSO_MAX_STATUS_BYTES];
    uint8_t mut[sizeof PIDV_ZLIB];
    size_t n = 0, i, rejected = 0, exact = 0, other = 0;
    printf("\n-- bounded inflate (RFC 1950/1951) --\n");
    CHECK(dsso_inflate(SB(PIDV_ZLIB, sizeof PIDV_ZLIB), out, sizeof out, &n) == DSSO_OK &&
          n == sizeof PIDV_ZLIB_PLAIN && !memcmp(out, PIDV_ZLIB_PLAIN, n),
          "inflate: the status bitstring round-trips byte-exactly");
    CHECK(dsso_inflate(SB(PIDV_ZLIB, sizeof PIDV_ZLIB), out, 2, &n) == DSSO_E_FORMAT,
          "inflate: a stream that would exceed the output cap is refused");
    CHECK(dsso_inflate(SB(PIDV_ZLIB, 4), out, sizeof out, &n) == DSSO_E_FORMAT,
          "inflate: a truncated stream is refused");
    {
        memcpy(mut, PIDV_ZLIB, sizeof mut);
        mut[sizeof mut - 1] ^= 0xFF;
        CHECK(dsso_inflate(SB(mut, sizeof mut), out, sizeof out, &n) == DSSO_E_FORMAT,
              "inflate: a wrong Adler-32 trailer is refused");
        memcpy(mut, PIDV_ZLIB, sizeof mut);
        mut[0] = 0x00;
        CHECK(dsso_inflate(SB(mut, sizeof mut), out, sizeof out, &n) == DSSO_E_FORMAT,
              "inflate: a bad zlib header is refused");
    }
    for (i = 0; i < 1500; ++i) {
        size_t k = rnd_below(sizeof mut);
        int rc;
        memcpy(mut, PIDV_ZLIB, sizeof mut);
        mut[k] = (uint8_t)(mut[k] ^ (1u << rnd_below(8)));
        n = 0xDEAD;
        rc = dsso_inflate(SB(mut, sizeof mut), out, sizeof out, &n);
        if (rc == DSSO_OK) {
            if (n == sizeof PIDV_ZLIB_PLAIN && !memcmp(out, PIDV_ZLIB_PLAIN, n)) exact++;
            else if (n <= sizeof out) other++;
            else { other++; g_fail++; }
        } else if (rc < 0 && n == 0xDEAD) {
            rejected++;
        } else {
            g_fail++;
        }
    }
    CHECK(rejected + exact + other == 1500,
          "inflate fuzz: 1500 single-bit mutants each returned a definite verdict");
    CHECK(rejected > 1000,
          "inflate fuzz: the overwhelming majority are rejected (the Adler-32 sees them)");
    printf("     [inflate fuzz: %lu rejected, %lu byte-identical, %lu other-but-bounded]\n",
           (unsigned long)rejected, (unsigned long)exact, (unsigned long)other);
}

/* ── section 5: the nine PID verification rules ───────────────────────────── */
typedef struct { const char *name; const char *text; int want; const char *note; } pid_case;

static void run_cases(const pid_case *c, size_t n, const char *nonce) {
    dsso_pid_policy pol = pol_with(nonce);
    dsso_pid_result res;
    size_t i;
    for (i = 0; i < n; ++i) {
        char msg[220];
        int rc = dsso_pid_verify(S(c[i].text), &pol, &res);
        snprintf(msg, sizeof msg, "%s -> %s (%s)", c[i].name,
                 dsso_status_name((dsso_status)c[i].want), c[i].note);
        g_checks++;
        if (rc == c[i].want) printf("  PASS: %s\n", msg);
        else {
            printf("  FAIL: %s [got %s]\n", msg, dsso_status_name((dsso_status)rc));
            g_fail++;
        }
        dsso_pid_result_scrub(&res);
    }
}

static const pid_case CASES[] = {
    /* rule 1 — structure */
    { "NO_TILDE",      PIDV_NO_TILDE,      DSSO_E_FORMAT,    "rule 1: not a combined-format presentation" },
    { "FOUR_DOTS",     PIDV_FOUR_DOTS,     DSSO_E_FORMAT,    "rule 1: a JWT with four segments" },
    { "B64_PAD",       PIDV_B64_PAD,       DSSO_E_FORMAT,    "rule 1: a byte outside the wire alphabet" },
    /* rule 2 — issuer trust (OIA_12) */
    { "ISS_UNKNOWN",   PIDV_ISS_UNKNOWN,   DSSO_E_TRUST,     "rule 2: issuer not on the trust anchor list" },
    { "KID_UNKNOWN",   PIDV_KID_UNKNOWN,   DSSO_E_TRUST,     "rule 2: key id not on the trust anchor list" },
    { "HDR_JWK",       PIDV_HDR_JWK,       DSSO_E_TRUST,     "rule 2: the token may not supply its own key" },
    { "HDR_X5C",       PIDV_HDR_X5C,       DSSO_E_TRUST,     "rule 2: nor its own certificate chain" },
    { "HDR_CRIT",      PIDV_HDR_CRIT,      DSSO_E_TRUST,     "rule 2: nor demand an unimplemented extension" },
    /* rule 3 — signature */
    { "ALG_NONE",      PIDV_ALG_NONE,      DSSO_E_CRYPTO,    "rule 3: alg: none" },
    { "ALG_HS256",     PIDV_ALG_HS256,     DSSO_E_CRYPTO,    "rule 3: algorithm substitution" },
    { "SIG_WRONG_KEY", PIDV_SIG_WRONG_KEY, DSSO_E_CRYPTO,    "rule 3: signed by another key" },
    { "SIG_OTHER_BYTES", PIDV_SIG_OTHER_BYTES, DSSO_E_CRYPTO, "rule 3: a real signature over other bytes" },
    { "SIG_TRUNC",     PIDV_SIG_TRUNC,     DSSO_E_FORMAT,    "rule 3: a truncated signature is not 64 bytes" },
    /* rule 4 — selective disclosure */
    { "DISC_NO_DIGEST", PIDV_DISC_NO_DIGEST, DSSO_E_FORMAT,  "rule 4: a disclosure matching no _sd digest" },
    { "DISC_DUP",      PIDV_DISC_DUP,      DSSO_E_FORMAT,    "rule 4: the same disclosure twice" },
    { "DISC_RESERVED", PIDV_DISC_RESERVED, DSSO_E_FORMAT,    "rule 4: a disclosure overwriting a registered claim" },
    { "DISC_SHADOW",   PIDV_DISC_SHADOW,   DSSO_E_FORMAT,    "rule 4: a disclosure shadowing a cleartext claim" },
    { "DISC_SHORT_SALT", PIDV_DISC_SHORT_SALT, DSSO_E_FORMAT, "rule 4: a salt below 128 bits" },
    { "SD_ALG_OTHER",  PIDV_SD_ALG_OTHER,  DSSO_E_FORMAT,    "rule 4: an _sd_alg this verifier does not implement" },
    /* rule 5 — holder binding (OIA_02) */
    { "KB_MISSING",    PIDV_KB_MISSING,    DSSO_E_BINDING,   "rule 5: no Key Binding JWT" },
    { "KB_OTHER_KEY",  PIDV_KB_OTHER_KEY,  DSSO_E_BINDING,   "rule 5: KB-JWT by a key the credential does not bind" },
    { "KB_REPLAY",     PIDV_KB_REPLAY,     DSSO_E_BINDING,   "rule 5: a KB-JWT lifted from another presentation" },
    { "NO_CNF",        PIDV_NO_CNF,        DSSO_E_BINDING,   "rule 5: the credential binds no holder key" },
    { "KB_TYP",        PIDV_KB_TYP,        DSSO_E_BINDING,   "rule 5: the KB-JWT is not typed kb+jwt" },
    /* rule 6 — audience and request binding */
    { "AUD_OTHER",     PIDV_AUD_OTHER,     DSSO_E_AUDIENCE,  "rule 6a: addressed to another relying party" },
    { "NONCE_OTHER",   PIDV_NONCE_OTHER,   DSSO_E_REPLAY,    "rule 6b: answering a different request" },
    /* rule 7 — freshness */
    { "EXPIRED",       PIDV_EXPIRED,       DSSO_E_EXPIRED,   "rule 7: past exp" },
    { "EXP_IN_SKEW",   PIDV_EXP_IN_SKEW,   DSSO_OK,          "rule 7: the configured skew tolerance is real, and stated" },
    { "FUTURE_IAT",    PIDV_FUTURE_IAT,    DSSO_E_EXPIRED,   "rule 7: issued in the future" },
    { "NBF_FUTURE",    PIDV_NBF_FUTURE,    DSSO_E_EXPIRED,   "rule 7: not yet valid" },
    { "CRED_ANCIENT",  PIDV_CRED_ANCIENT,  DSSO_E_EXPIRED,   "rule 7: implausibly old credential" },
    { "KB_STALE",      PIDV_KB_STALE,      DSSO_E_EXPIRED,   "rule 7: presentation older than max_pres_age" },
    /* rule 8 — status (Token Status List) */
    { "REVOKED",       PIDV_REVOKED,       DSSO_E_STATUS,    "rule 8: revoked" },
    { "SUSPENDED",     PIDV_SUSPENDED,     DSSO_E_STATUS,    "rule 8: suspended" },
    { "STATUS_STALE",  PIDV_STATUS_STALE,  DSSO_E_UNAVAILABLE, "rule 8: status token past its own exp — FAILS CLOSED" },
    { "STATUS_WRONGSUB", PIDV_STATUS_WRONGSUB, DSSO_E_UNAVAILABLE, "rule 8: a different list's token — FAILS CLOSED" },
    { "STATUS_UNTRUSTED", PIDV_STATUS_UNTRUSTED, DSSO_E_TRUST, "rule 8: status token signed off the trust list" },
    { "STATUS_UNAVAIL", PIDV_STATUS_UNAVAIL, DSSO_E_UNAVAILABLE, "rule 8: list unreachable — FAILS CLOSED" },
    { "STATUS_OOR",    PIDV_STATUS_OOR,    DSSO_E_UNAVAILABLE, "rule 8: index past the bitstring — FAILS CLOSED" },
    { "STATUS_BOMB",   PIDV_STATUS_BOMB,   DSSO_E_UNAVAILABLE, "rule 8: a decompression bomb — FAILS CLOSED" },
    { "STATUS_CROSSISS", PIDV_STATUS_CROSSISS, DSSO_E_TRUST, "rule 8: another trusted PID Provider may not answer for this issuer" },
    { "NO_STATUS",     PIDV_NO_STATUS,     DSSO_E_FORMAT,    "rule 8: no status information at all" },
    /* rule 9 — assurance */
    { "LOA_SUBSTANTIAL", PIDV_LOA_SUBSTANTIAL, DSSO_E_ASSURANCE, "rule 9: below the required level" },
    { "LOA_ABSENT",    PIDV_LOA_ABSENT,    DSSO_E_ASSURANCE, "rule 9: no level asserted" },
    { "LOA_UNKNOWN",   PIDV_LOA_UNKNOWN,   DSSO_E_ASSURANCE, "rule 9: an unrecognised level" },
    { "LOA_CAPPED",    PIDV_LOA_CAPPED,    DSSO_E_ASSURANCE, "rule 9: the anchor caps what its issuer may assert" }
};

static void test_pipeline(void) {
    dsso_pid_policy pol = pol_with(PIDV_NONCE);
    dsso_pid_result res, res2;
    dsso_slice v;
    uint8_t material[320];
    size_t mlen = 0;

    printf("\n-- PID presentation: the accept case --\n");
    CHECK(dsso_pid_verify(S(PIDV_OK), &pol, &res) == DSSO_OK,
          "accept: a conforming SD-JWT VC PID presentation verifies");
    CHECK(res.n_claims == 4, "accept: exactly the four disclosed attributes are returned");
    CHECK(dsso_pid_claim_value(&res, "family_name", &v) == DSSO_OK &&
          v.n == 9 && !memcmp(v.p, "\"Petrova\"", 9),
          "accept: a disclosed attribute carries its issuer-digested value");
    CHECK(dsso_pid_claim_value(&res, "birth_place", &v) == DSSO_E_FORMAT,
          "accept: an undisclosed attribute is absent, never fabricated");
    CHECK(res.loa == DSSO_LOA_HIGH, "accept: the effective assurance level is recorded");
    CHECK(dsso_pid_subject_material(&res, material, sizeof material, &mlen) == DSSO_OK && mlen > 0,
          "accept: subject material is derivable from the disclosed attributes");

    printf("\n-- PID presentation: rejections, one per rule --\n");
    run_cases(CASES, sizeof CASES / sizeof CASES[0], PIDV_NONCE);

    printf("\n-- ECDSA malleability, stated rather than assumed --\n");
    CHECK(dsso_pid_verify(S(PIDV_SIG_HIGH_S), &pol, &res2) == DSSO_OK,
          "malleability: the (r, n-s) twin also verifies — ECDSA is malleable and "
          "this verifier does not pretend otherwise");
    CHECK(res2.n_claims == res.n_claims && res2.loa == res.loa,
          "malleability: the malleated twin yields the SAME claims — a second byte "
          "string, not a second identity");
    CHECK(strcmp(PIDV_OK, PIDV_SIG_HIGH_S) != 0,
          "malleability: the twin really is a different byte string");

    printf("\n-- a failed verification leaves nothing behind --\n");
    {
        dsso_pid_result dirty;
        size_t i, nonzero = 0;
        memset(&dirty, 0xAB, sizeof dirty);
        CHECK(dsso_pid_verify(S(PIDV_REVOKED), &pol, &dirty) == DSSO_E_STATUS,
              "scrub: a revoked credential is rejected");
        for (i = 0; i < sizeof dirty; ++i) nonzero |= ((const uint8_t *)&dirty)[i];
        CHECK(nonzero == 0,
              "scrub: the result is zeroed on failure, so a caller that ignores the "
              "status reads no claims");
    }
    {
        /* Rule 6b with the RIGHT nonce for a DIFFERENT request: the same bytes
         * accepted under one challenge are rejected under another. */
        dsso_pid_policy p2 = pol_with(PIDV_NONCE2);
        CHECK(dsso_pid_verify(S(PIDV_OK), &p2, &res2) == DSSO_E_REPLAY,
              "rule 6b: a presentation valid for request A is rejected for request B");
    }
    {
        dsso_pid_policy p3 = pol_with(PIDV_NONCE);
        p3.required_loa = DSSO_LOA_SUBSTANTIAL;
        CHECK(dsso_pid_verify(S(PIDV_LOA_SUBSTANTIAL), &p3, &res2) == DSSO_OK,
              "rule 9: the same credential is accepted when substantial is enough");
    }
    {
        dsso_pid_policy p4 = pol_with(PIDV_NONCE);
        p4.fetch = NULL;
        CHECK(dsso_pid_verify(S(PIDV_OK), &p4, &res2) == DSSO_E_UNAVAILABLE,
              "rule 8: with no way to consult the status list at all, FAIL CLOSED");
    }
    {
        /* The trust anchor list is the only source of issuer keys: empty it and
         * the very same presentation stops verifying. */
        dsso_trust_list empty;
        dsso_pid_policy p5 = pol_with(PIDV_NONCE);
        empty.a = g_anchors; empty.n = 0;
        p5.trust = &empty;
        CHECK(dsso_pid_verify(S(PIDV_OK), &p5, &res2) == DSSO_E_TRUST,
              "rule 2: with an empty trust anchor list nothing verifies (OIA_12)");
    }
    {
        /* The anchor's key really is the one used: corrupt it and the signature
         * check fails, which is what proves the key came from the list. */
        dsso_trust_anchor bent[3];
        dsso_trust_list bl;
        dsso_pid_policy p6 = pol_with(PIDV_NONCE);
        memcpy(bent, g_anchors, sizeof bent);
        bent[0].pk[40] ^= 0x01;
        bl.a = bent; bl.n = 3;
        p6.trust = &bl;
        CHECK(dsso_pid_verify(S(PIDV_OK), &p6, &res2) == DSSO_E_CRYPTO,
              "rule 2+3: the anchor's key is the key actually used to verify");
    }
    dsso_pid_result_scrub(&res);
    dsso_pid_result_scrub(&res2);
}

/* ── section 6: the presentation fuzz arm ─────────────────────────────────── */
#define FUZZ_CANARY 0x5A
static void test_fuzz_presentation(void) {
    static uint8_t arena[64 + DSSO_MAX_TOKEN + 64];
    uint8_t *body = arena + 64;
    const size_t base_len = sizeof PIDV_OK - 1;
    dsso_pid_policy pol = pol_with(PIDV_NONCE);
    dsso_pid_result res;
    size_t i, accepted = 0, rejected = 0, canary_bad = 0, identical = 0;
    int bad_status = 0;

    printf("\n-- fuzz: 2400 mutated presentations --\n");
    for (i = 0; i < 2400; ++i) {
        size_t len = base_len, k;
        int rc, kind = (int)rnd_below(5);
        memset(arena, FUZZ_CANARY, sizeof arena);
        memcpy(body, PIDV_OK, base_len);
        switch (kind) {
            case 0:                                          /* flip a bit */
                k = rnd_below(len);
                body[k] = (uint8_t)(body[k] ^ (1u << rnd_below(8)));
                break;
            case 1:                                          /* truncate */
                len = rnd_below(len);
                break;
            case 2:                                          /* delete a byte */
                k = rnd_below(len);
                memmove(body + k, body + k + 1, len - k - 1);
                len--;
                break;
            case 3:                                          /* insert a byte */
                k = rnd_below(len);
                memmove(body + k + 1, body + k, len - k);
                body[k] = (uint8_t)rnd_below(256);
                len++;
                break;
            default: {                                       /* splice a chunk */
                size_t src = rnd_below(len), n = 1 + rnd_below(32);
                if (src + n > len) n = len - src;
                k = rnd_below(len);
                if (k + n > len) n = len - k;
                memmove(body + k, body + src, n);
                break;
            }
        }
        if (len == base_len && memcmp(body, PIDV_OK, base_len) == 0) { identical++; continue; }
        rc = dsso_pid_verify(SB(body, len), &pol, &res);
        if (rc == DSSO_OK) accepted++;
        else if (rc < 0) rejected++;
        else bad_status = 1;
        dsso_pid_result_scrub(&res);
        for (k = 0; k < 64; ++k)
            if (arena[k] != FUZZ_CANARY || arena[64 + DSSO_MAX_TOKEN + k] != FUZZ_CANARY)
                canary_bad++;
    }
    CHECK(bad_status == 0, "fuzz: every mutant returned a dsso_status, never a stray value");
    CHECK(canary_bad == 0, "fuzz: the guard bytes either side of the input are untouched");
    CHECK(accepted == 0,
          "fuzz: NO mutant that differs from the original was accepted — every byte of "
          "a presentation is covered by a signature or by sd_hash");
    CHECK(rejected + identical == 2400, "fuzz: 2400 mutants, all accounted for");
    printf("     [presentation fuzz: %lu rejected, %lu no-op mutations, %lu accepted]\n",
           (unsigned long)rejected, (unsigned long)identical, (unsigned long)accepted);
}

static void test_fuzz_json(void) {
    static uint8_t arena[64 + 512 + 64];
    uint8_t *body = arena + 64;
    const size_t base_len = sizeof FUZZ_JSON - 1;
    size_t i, ok = 0, rej = 0, canary_bad = 0;
    int bad_status = 0, walk_bad = 0;

    printf("\n-- fuzz: 3000 mutated JSON documents --\n");
    for (i = 0; i < 3000; ++i) {
        size_t len = base_len, k;
        dsso_slice root;
        dsso_json_type t;
        int rc, kind = (int)rnd_below(4);
        memset(arena, FUZZ_CANARY, sizeof arena);
        memcpy(body, FUZZ_JSON, base_len);
        switch (kind) {
            case 0: k = rnd_below(len); body[k] = (uint8_t)rnd_below(256); break;
            case 1: len = rnd_below(len); break;
            case 2: k = rnd_below(len); memmove(body + k, body + k + 1, len - k - 1); len--; break;
            default: k = rnd_below(len); memmove(body + k + 1, body + k, len - k);
                     body[k] = (uint8_t)rnd_below(256); len++; break;
        }
        rc = dsso_json_validate(SB(body, len), &root, &t);
        if (rc == DSSO_OK) {
            /* A document that validated must also be walkable without incident. */
            size_t cnt = 0;
            dsso_slice v;
            dsso_json_type vt;
            ok++;
            if (root.p < body || root.p + root.n > body + len) walk_bad = 1;
            if (t == DSSO_JSON_OBJECT) {
                (void)dsso_json_member(root, "iss", &v, &vt);
                (void)dsso_json_member(root, "n", &v, &vt);
                (void)dsso_json_member(root, "zzz", &v, &vt);
            } else if (t == DSSO_JSON_ARRAY) {
                (void)dsso_json_array_len(root, &cnt);
                for (k = 0; k < cnt && k < 8; ++k) (void)dsso_json_element(root, k, &v, &vt);
            }
        } else if (rc == DSSO_E_FORMAT || rc == DSSO_E_ARG) {
            rej++;
        } else {
            bad_status = 1;
        }
        for (k = 0; k < 64; ++k)
            if (arena[k] != FUZZ_CANARY || arena[64 + 512 + k] != FUZZ_CANARY) canary_bad++;
    }
    CHECK(bad_status == 0, "json fuzz: every mutant returned DSSO_OK or a bounded failure");
    CHECK(canary_bad == 0, "json fuzz: the guard bytes either side of the document are untouched");
    CHECK(walk_bad == 0, "json fuzz: an accepted root span always lies inside the input");
    CHECK(ok + rej == 3000, "json fuzz: 3000 mutants, all accounted for");
    printf("     [json fuzz: %lu accepted-and-walked, %lu rejected]\n",
           (unsigned long)ok, (unsigned long)rej);
}

static void test_fuzz_b64(void) {
    static uint8_t arena[64 + 256 + 64];
    uint8_t *body = arena + 64;
    static const char B64SEED[] = "eyJhbGciOiJFUzI1NiIsImtpZCI6Im1zLXBpZCJ9";
    const size_t base_len = sizeof B64SEED - 1;
    uint8_t out[256];
    size_t i, ok = 0, rej = 0, canary_bad = 0;
    int bad = 0;

    printf("\n-- fuzz: 1500 mutated base64url strings --\n");
    for (i = 0; i < 1500; ++i) {
        size_t len = base_len, k, n = 0;
        int rc;
        memset(arena, FUZZ_CANARY, sizeof arena);
        memcpy(body, B64SEED, base_len);
        if (rnd_below(2)) { k = rnd_below(len); body[k] = (uint8_t)rnd_below(256); }
        else len = rnd_below(len + 1);
        rc = dsso_b64url_decode(SB(body, len), out, sizeof out, &n);
        if (rc == DSSO_OK) {
            ok++;
            /* The only encodings accepted are canonical, so the decoded length
             * is a pure function of the input length. */
            if (n != len / 4 * 3 + (len % 4 ? len % 4 - 1 : 0)) bad = 1;
        } else if (rc == DSSO_E_FORMAT || rc == DSSO_E_ARG) rej++;
        else bad = 1;
        for (k = 0; k < 64; ++k)
            if (arena[k] != FUZZ_CANARY || arena[64 + 256 + k] != FUZZ_CANARY) canary_bad++;
    }
    CHECK(bad == 0, "b64url fuzz: every accepted decode has the length its input dictates");
    CHECK(canary_bad == 0, "b64url fuzz: the guard bytes either side of the input are untouched");
    CHECK(ok + rej == 1500, "b64url fuzz: 1500 mutants, all accounted for");
    printf("     [b64url fuzz: %lu accepted, %lu rejected]\n",
           (unsigned long)ok, (unsigned long)rej);
}

/* ── section 7: the account-binding rules ─────────────────────────────────── */
static const uint8_t ACC_A[32] = { 'A','C','C','O','U','N','T','-','A',0 };
static const uint8_t ACC_B[32] = { 'A','C','C','O','U','N','T','-','B',0 };
static const uint8_t AUTHKEY_A[32] = { 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,
                                       17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32 };
static const uint8_t AUTHKEY_B[32] = { 32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,
                                       16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1 };
static const uint8_t PSEU_KEY[32] = { 0xC0,0xFF,0xEE,0xBA,0xBE,0,0,0,0,0,0,0,0,0,0,0,
                                      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 };

/* Build the account holder's own re-authentication proof — the thing a stolen
 * session does NOT give an attacker. */
static dsso_account_auth mk_auth(const uint8_t *acct, const uint8_t *key,
                                 int64_t at, dsso_auth_kind kind, int corrupt);

static void test_binding(void) {
    dsso_bind_ctx ctx;
    dsso_pid_policy base = pol_with(PIDV_NONCE);      /* nonce is overridden */
    dsso_account_auth fresh_a, fresh_b, session_a, stale_a, forged_a;
    uint8_t pseu_a[32], pseu_a2[32], pseu_b[32], tmp[32];

    printf("\n-- account binding: rules, and the three things that must be impossible --\n");
    CHECK(dsso_bind_init(&ctx, PSEU_KEY, 300, 120) == DSSO_OK, "bind: context initialises");
    CHECK(dsso_bind_account_add(&ctx, ACC_A, AUTHKEY_A) == DSSO_OK, "bind: account A exists");
    CHECK(dsso_bind_account_add(&ctx, ACC_B, AUTHKEY_B) == DSSO_OK, "bind: account B exists");

    fresh_a   = mk_auth(ACC_A, AUTHKEY_A, PIDV_NOW - 10, DSSO_AUTH_FRESH, 0);
    fresh_b   = mk_auth(ACC_B, AUTHKEY_B, PIDV_NOW - 10, DSSO_AUTH_FRESH, 0);
    session_a = mk_auth(ACC_A, AUTHKEY_A, PIDV_NOW - 10, DSSO_AUTH_SESSION_ONLY, 0);
    stale_a   = mk_auth(ACC_A, AUTHKEY_A, PIDV_NOW - 9999, DSSO_AUTH_FRESH, 0);
    forged_a  = mk_auth(ACC_A, AUTHKEY_A, PIDV_NOW - 10, DSSO_AUTH_FRESH, 1);

    /* (i) A SESSION IS NOT AUTHORISATION. */
    CHECK(dsso_bind_challenge_new(&ctx, ACC_A, &session_a, DSSO_BIND_PURPOSE_BIND,
                                  (const uint8_t *)PIDV_BIND_NONCE, PIDV_NOW) == DSSO_E_BINDING,
          "bind (i): a DSSO session ALONE does not authorise opening a binding");
    CHECK(dsso_bind_challenge_new(&ctx, ACC_A, NULL, DSSO_BIND_PURPOSE_BIND,
                                  (const uint8_t *)PIDV_BIND_NONCE, PIDV_NOW) == DSSO_E_BINDING,
          "bind (i): no account authentication at all is refused");
    CHECK(dsso_bind_challenge_new(&ctx, ACC_A, &forged_a, DSSO_BIND_PURPOSE_BIND,
                                  (const uint8_t *)PIDV_BIND_NONCE, PIDV_NOW) == DSSO_E_BINDING,
          "bind (i): a re-auth proof under the wrong key is refused");
    CHECK(dsso_bind_challenge_new(&ctx, ACC_A, &stale_a, DSSO_BIND_PURPOSE_BIND,
                                  (const uint8_t *)PIDV_BIND_NONCE, PIDV_NOW) == DSSO_E_EXPIRED,
          "bind (i): a re-auth proof outside the window is refused");
    CHECK(dsso_bind_challenge_new(&ctx, ACC_A, &fresh_b, DSSO_BIND_PURPOSE_BIND,
                                  (const uint8_t *)PIDV_BIND_NONCE, PIDV_NOW) == DSSO_E_BINDING,
          "bind (i): B's re-auth proof does not open a challenge on A");

    /* A presentation without an open challenge binds nothing. */
    CHECK(dsso_bind_commit(&ctx, ACC_A, S(PIDV_OK_BINDNONCE), &base, PIDV_NOW, pseu_a)
              == DSSO_E_REPLAY,
          "bind (iii): a presentation with no open challenge is refused");

    /* The happy path. */
    CHECK(dsso_bind_challenge_new(&ctx, ACC_A, &fresh_a, DSSO_BIND_PURPOSE_BIND,
                                  (const uint8_t *)PIDV_BIND_NONCE, PIDV_NOW) == DSSO_OK,
          "bind: a fresh account authentication opens a binding challenge");
    CHECK(dsso_bind_commit(&ctx, ACC_A, S(PIDV_OK_BINDNONCE), &base, PIDV_NOW, pseu_a) == DSSO_OK,
          "bind: a presentation answering THAT challenge binds the subject to A");
    CHECK(dsso_bind_lookup(&ctx, ACC_A, tmp) == DSSO_OK && !memcmp(tmp, pseu_a, 32),
          "bind: the account now resolves to the stored pseudonym");

    /* (iii) NO REUSE: the same presentation, again. */
    CHECK(dsso_bind_commit(&ctx, ACC_A, S(PIDV_OK_BINDNONCE), &base, PIDV_NOW, pseu_a2)
              == DSSO_E_REPLAY,
          "bind (iii): the challenge is consumed — the same presentation cannot be replayed");
    CHECK(dsso_bind_challenge_new(&ctx, ACC_B, &fresh_b, DSSO_BIND_PURPOSE_BIND,
                                  (const uint8_t *)PIDV_BIND_NONCE, PIDV_NOW) == DSSO_OK &&
          dsso_bind_commit(&ctx, ACC_B, S(PIDV_OK_BINDNONCE), &base, PIDV_NOW, pseu_a2)
              == DSSO_E_BINDING,
          "bind (ii): the same subject cannot also be bound to account B");

    /* A stale challenge. */
    CHECK(dsso_bind_challenge_new(&ctx, ACC_B, &fresh_b, DSSO_BIND_PURPOSE_BIND,
                                  (const uint8_t *)PIDV_BIND_NONCE, PIDV_NOW) == DSSO_OK &&
          dsso_bind_commit(&ctx, ACC_B, S(PIDV_OK_BINDNONCE), &base, PIDV_NOW + 1000, pseu_a2)
              == DSSO_E_EXPIRED,
          "bind (iii): a challenge older than its TTL is refused");

    /* (ii) NO SILENT RE-BIND: a different person onto an already-bound account. */
    CHECK(dsso_bind_challenge_new(&ctx, ACC_A, &fresh_a, DSSO_BIND_PURPOSE_BIND,
                                  (const uint8_t *)PIDV_BIND_NONCE, PIDV_NOW) == DSSO_OK &&
          dsso_bind_commit(&ctx, ACC_A, S(PIDV_SUBJECT_B_BINDNONCE), &base, PIDV_NOW, pseu_b)
              == DSSO_E_BINDING,
          "bind (ii): another person cannot be re-bound onto A without an explicit unbind");
    CHECK(dsso_bind_lookup(&ctx, ACC_A, tmp) == DSSO_OK && !memcmp(tmp, pseu_a, 32),
          "bind (ii): the refused re-bind changed nothing");

    /* Re-affirmation of the same subject is idempotent, not a second binding. */
    CHECK(dsso_bind_challenge_new(&ctx, ACC_A, &fresh_a, DSSO_BIND_PURPOSE_BIND,
                                  (const uint8_t *)PIDV_BIND_NONCE, PIDV_NOW) == DSSO_OK &&
          dsso_bind_commit(&ctx, ACC_A, S(PIDV_OK_BINDNONCE), &base, PIDV_NOW, pseu_a2) == DSSO_OK &&
          !memcmp(pseu_a, pseu_a2, 32),
          "bind: re-presenting the SAME subject for the SAME account is idempotent");

    /* Unbind needs the same fresh authentication; then re-binding works. */
    CHECK(dsso_bind_unbind(&ctx, ACC_A, &session_a, PIDV_NOW) == DSSO_E_BINDING,
          "unbind: a session alone does not authorise unbinding either");
    CHECK(dsso_bind_unbind(&ctx, ACC_A, &fresh_a, PIDV_NOW) == DSSO_OK,
          "unbind: a fresh account authentication unbinds");
    CHECK(dsso_bind_lookup(&ctx, ACC_A, tmp) == DSSO_E_BINDING,
          "unbind: the account no longer resolves to a subject");
    CHECK(dsso_bind_unbind(&ctx, ACC_A, &fresh_a, PIDV_NOW) == DSSO_E_BINDING,
          "unbind: unbinding twice is refused");
    CHECK(dsso_bind_challenge_new(&ctx, ACC_A, &fresh_a, DSSO_BIND_PURPOSE_BIND,
                                  (const uint8_t *)PIDV_BIND_NONCE, PIDV_NOW) == DSSO_OK &&
          dsso_bind_commit(&ctx, ACC_A, S(PIDV_SUBJECT_B_BINDNONCE), &base, PIDV_NOW, pseu_b)
              == DSSO_OK,
          "re-bind: after the explicit unbind, another person MAY be bound");
    CHECK(memcmp(pseu_a, pseu_b, 32) != 0, "re-bind: the two subjects have distinct pseudonyms");

    /* The binding layer refuses a presentation that fails ANY verification rule. */
    CHECK(dsso_bind_challenge_new(&ctx, ACC_B, &fresh_b, DSSO_BIND_PURPOSE_BIND,
                                  (const uint8_t *)PIDV_BIND_NONCE, PIDV_NOW) == DSSO_OK &&
          dsso_bind_commit(&ctx, ACC_B, S(PIDV_OK), &base, PIDV_NOW, pseu_a2) == DSSO_E_REPLAY,
          "bind: a presentation answering some OTHER challenge is refused (nonce is the "
          "challenge record's, not the caller's)");
    {
        /* A subject with nothing to derive a pseudonym from. */
        dsso_pid_policy p = pol_with(PIDV_NONCE);
        dsso_pid_result r;
        uint8_t m[320];
        size_t ml = 0;
        CHECK(dsso_pid_verify(S(PIDV_NO_PAN), &p, &r) == DSSO_OK,
              "bind: a presentation without the administrative number still VERIFIES");
        CHECK(dsso_pid_subject_material(&r, m, sizeof m, &ml) == DSSO_E_FORMAT,
              "bind: but it yields no subject material, so it binds nothing");
        dsso_pid_result_scrub(&r);
    }
}

static dsso_account_auth mk_auth(const uint8_t *acct, const uint8_t *key,
                                 int64_t at, dsso_auth_kind kind, int corrupt) {
    /* The proof shape dsso_bind.c recomputes. Building it here (rather than
     * exporting a helper) keeps the gate from asserting through the code it is
     * testing. */
    dsso_account_auth a;
    uint8_t msg[19 + 32 + 8];
    uint64_t v = (uint64_t)at;
    int i;
    size_t o = 0;
    memset(&a, 0, sizeof a);
    a.kind = kind;
    a.at   = at;
    memcpy(msg, "DSSO-ACCT-REAUTH-v1", 19); o = 19;
    memcpy(msg + o, acct, 32); o += 32;
    for (i = 7; i >= 0; --i) msg[o++] = (uint8_t)((v >> (8 * i)) & 0xFFu);
    determ_hmac_sha256(key, 32, msg, o, a.mac);
    if (corrupt) a.mac[0] ^= 0x01;
    return a;
}

/* ── section 8: the pseudonym ─────────────────────────────────────────────── */
static void test_pseudonym(void) {
    uint8_t k1[32], k2[32], a[32], b[32], c[32];
    static const uint8_t M1[] = { 3, 'i','s','s', 4, '9','2','0','4' };
    static const uint8_t M2[] = { 4, 'i','s','s','9', 3, '2','0','4' };
    size_t i;
    printf("\n-- pseudonym derivation --\n");
    memset(k1, 0x11, 32);
    memset(k2, 0x12, 32);
    CHECK(dsso_pseudonym_derive(k1, M1, sizeof M1, a) == DSSO_OK &&
          dsso_pseudonym_derive(k1, M1, sizeof M1, b) == DSSO_OK && !memcmp(a, b, 32),
          "pseudonym: the same subject always derives the same value");
    CHECK(dsso_pseudonym_derive(k2, M1, sizeof M1, c) == DSSO_OK && memcmp(a, c, 32) != 0,
          "pseudonym: a different service key gives an unrelated value — a leaked "
          "database without the key is not an identity list");
    CHECK(dsso_pseudonym_derive(k1, M2, sizeof M2, c) == DSSO_OK && memcmp(a, c, 32) != 0,
          "pseudonym: length separation — (iss,id) pairs cannot be re-split to collide");
    {
        int nonzero = 0;
        for (i = 0; i < 32; ++i) nonzero |= a[i];
        CHECK(nonzero != 0, "pseudonym: the derivation produces a non-trivial value");
    }
    CHECK(dsso_pseudonym_derive(k1, NULL, 400, a) == DSSO_E_ARG,
          "pseudonym: over-long material is refused rather than truncated");
}

int dsso_selftest_pid(void) {
    trust_init();
    printf("determ-dsso selftest-pid — EUDI PID presentations as a Wallet-Relying Party\n");
    printf("  format: SD-JWT VC (JOSE/JSON) with a Key Binding JWT; ISO/IEC 18013-5 mdoc\n");
    printf("  is NOT implemented, so an mdoc-only wallet is out of scope.\n");
    test_b64url();
    test_json();
    test_es256();
    test_inflate();
    test_pipeline();
    test_fuzz_presentation();
    test_fuzz_json();
    test_fuzz_b64();
    test_binding();
    test_pseudonym();
    printf("\n  %s: dsso-pid %s (%d checks)\n", g_fail == 0 ? "PASS" : "FAIL",
           g_fail == 0 ? "all assertions" : "had failures", g_checks);
    return g_fail == 0 ? 0 : 1;
}
