#!/usr/bin/env bash
# determ-wallet state-proof-verify CLI test.
#
# Verifies the OFFLINE Merkle state-proof verifier — the wallet-side dual
# of the daemon's `state_proof` RPC and determ-light `verify-state-proof`.
# The command takes a state-proof JSON (the shape returned by the
# `state_proof` RPC, PROTOCOL.md §10.2) plus an operator-supplied 32-byte
# `state_root` and reports VALID/INVALID by recomputing the Merkle root
# from the leaf + sibling path entirely in-process (no RPC, no network,
# no subprocess).
#
# Fixtures are generated by an independent Python reference implementation
# of the SAME documented Merkle algorithm (src/crypto/merkle.cpp):
#   leaf_hash  = SHA-256(0x00 || u32_be(key_len) || key || value_hash)
#   inner_hash = SHA-256(0x01 || left || right)
#   balanced binary tree, duplicate-last to even each odd level.
# So a VALID fixture carries a genuinely-correct root + sibling path and
# the wallet's verdict is cross-checked against an independent computation.
#
# Covers (~26 assertions):
#   1.  --help text exists + documents every flag.
#   2.  Global help dispatcher lists state-proof-verify.
#   3.  Missing --in → exit 1.
#   4.  Missing --root → exit 1.
#   5.  --root wrong length → exit 1.
#   6.  --root non-hex → exit 1.
#   7.  Unknown flag → exit 1.
#   8.  File not found → exit 1.
#   9.  Malformed JSON → exit 1 + malformed_proof.
#  10.  Proof missing a required field → exit 1 + malformed_proof.
#  11.  Proof carrying an {"error":...} envelope → exit 1.
#  12.  Happy path (single-leaf tree) VALID → exit 0.
#  13.  Happy path (multi-leaf tree) VALID → exit 0.
#  14.  --json happy path: strict schema + valid:true.
#  15.  Wrong --root → exit 2 INVALID.
#  16.  Tampered value_hash → exit 2 INVALID.
#  17.  Proof's self state_root disagrees with --root → exit 2.
#  18.  Mixed-case --root still VALID (normalized).
#  19.  Human output prints labelled fields + VALID verdict.
#
# Run from repo root: bash tools/test_wallet_state_proof_verify.sh
set -u
cd "$(dirname "$0")/.."
source tools/common.sh

if [ -z "${DETERM_WALLET:-}" ] || [ ! -x "$DETERM_WALLET" ]; then
    echo "  SKIP: determ-wallet binary not found; build with"
    echo "        cmake --build build --config Release --target determ-wallet"
    exit 0
fi

WALLET="$DETERM_WALLET"
SCRATCH="build/test_wallet_state_proof_verify.$$"
mkdir -p "$SCRATCH"
trap 'rm -rf "$SCRATCH"' EXIT

PY=python
command -v python >/dev/null 2>&1 || PY=python3

pass_count=0; fail_count=0
assert_eq() {
  if [ "$1" = "$2" ]; then echo "  PASS: $3"; pass_count=$((pass_count + 1))
  else echo "  FAIL: $3"; echo "       expected: $2"; echo "       got:      $1"; fail_count=$((fail_count + 1)); fi
}
assert_contains() {
  if echo "$1" | grep -q -- "$2"; then echo "  PASS: $3"; pass_count=$((pass_count + 1))
  else echo "  FAIL: $3"; echo "       missing substring: $2"; fail_count=$((fail_count + 1)); fi
}

# ── Reference fixture generator (independent Merkle implementation) ───────────
# Emits, for a given namespace + list of "keyhex:valhex" leaves and a
# target key, a state-proof JSON to <out> and prints the computed root on
# stdout. The implementation MUST match src/crypto/merkle.cpp exactly.
gen_proof() {
  # args: <out_json> <target_key_hex> <ns> <keyhex:valhex> [<keyhex:valhex> ...]
  local out="$1"; shift
  local target="$1"; shift
  local ns="$1"; shift
  local leaves="$*"
  $PY - "$out" "$target" "$ns" $leaves <<'PYEOF'
import sys, json, hashlib, struct

out, target_hex, ns = sys.argv[1], sys.argv[2], sys.argv[3]
pairs = []
for spec in sys.argv[4:]:
    k, v = spec.split(":")
    pairs.append((bytes.fromhex(k), bytes.fromhex(v)))

def leaf_hash(key, vh):
    return hashlib.sha256(b"\x00" + struct.pack(">I", len(key)) + key + vh).digest()

def inner_hash(l, r):
    return hashlib.sha256(b"\x01" + l + r).digest()

# sort by key (lexicographic byte order) — matches merkle_root
pairs.sort(key=lambda p: p[0])
leaf_count = len(pairs)
target = bytes.fromhex(target_hex)
target_index = next(i for i, (k, _) in enumerate(pairs) if k == target)

# build proof = sibling hashes leaf->root, duplicating last on odd rows
row = [leaf_hash(k, v) for (k, v) in pairs]
idx = target_index
proof = []
while len(row) > 1:
    if len(row) % 2 == 1:
        row.append(row[-1])
    sib = idx + 1 if idx % 2 == 0 else idx - 1
    proof.append(row[sib])
    nxt = [inner_hash(row[i], row[i+1]) for i in range(0, len(row), 2)]
    row = nxt
    idx //= 2
root = row[0]
# S-040: the committed state_root wraps the inner root with the leaf count:
# SHA-256(0x02 || u32_be(leaf_count) || inner_root). Match the daemon convention.
root = hashlib.sha256(b"\x02" + struct.pack(">I", leaf_count) + root).digest()

tk, tv = pairs[target_index]
# value_hash is the committed value-hash leaf field directly (already a
# 32-byte hash in our fixtures), matching how the state_proof RPC returns it.
doc = {
    "state_root":  root.hex(),
    "namespace":   ns,
    "key_bytes":   tk.hex(),
    "value_hash":  tv.hex(),
    "target_index": target_index,
    "leaf_count":  leaf_count,
    "proof":       [h.hex() for h in proof],
    "height":      123,
}
with open(out, "w") as f:
    json.dump(doc, f)
print(root.hex())
PYEOF
}

# 32-byte value hashes (arbitrary but fixed) for fixtures.
VH_A="1111111111111111111111111111111111111111111111111111111111111111"
VH_B="2222222222222222222222222222222222222222222222222222222222222222"
VH_C="3333333333333333333333333333333333333333333333333333333333333333"
VH_D="4444444444444444444444444444444444444444444444444444444444444444"
# keys (opaque bytes, hex) — e.g. "a:" namespace account keys.
K_A="6100"   # "a\0"
K_B="6200"   # "b\0"
K_C="6300"   # "c\0"
K_D="6400"   # "d\0"

# Single-leaf tree fixture (root == leaf_hash, empty proof).
SINGLE="$SCRATCH/single.json"
ROOT_SINGLE=$(gen_proof "$SINGLE" "$K_A" "a" "$K_A:$VH_A")
echo "  fixture: ROOT_SINGLE=$ROOT_SINGLE"

# Multi-leaf (4-leaf) tree fixture, proving leaf C.
MULTI="$SCRATCH/multi.json"
ROOT_MULTI=$(gen_proof "$MULTI" "$K_C" "a" \
              "$K_A:$VH_A" "$K_B:$VH_B" "$K_C:$VH_C" "$K_D:$VH_D")
echo "  fixture: ROOT_MULTI=$ROOT_MULTI"

# ── 1. --help text ────────────────────────────────────────────────────────────
echo
echo "=== 1. --help text ==="
HELP=$("$WALLET" state-proof-verify --help 2>&1 | tr -d '\r')
assert_contains "$HELP" "Usage: determ-wallet state-proof-verify" "help shows synopsis"
assert_contains "$HELP" "OFFLINE Merkle state-proof verifier"      "help describes purpose"
assert_contains "$HELP" "\-\-in <proof.json>"                      "help documents --in"
assert_contains "$HELP" "\-\-root <hex64>"                         "help documents --root"
assert_contains "$HELP" "\-\-json"                                 "help documents --json"
assert_contains "$HELP" "S-040"                                    "help carries the S-040 caveat"

# ── 2. Global help dispatcher ─────────────────────────────────────────────────
echo
echo "=== 2. Global help mentions state-proof-verify ==="
GLOBAL=$("$WALLET" help 2>&1 | tr -d '\r')
assert_contains "$GLOBAL" "state-proof-verify" "global help lists state-proof-verify"

# ── 3. Missing --in → exit 1 ──────────────────────────────────────────────────
echo
echo "=== 3. Missing --in → exit 1 ==="
set +e
ERR=$("$WALLET" state-proof-verify --root "$ROOT_SINGLE" 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing --in exits 1"
assert_contains "$(echo "$ERR" | tr -d '\r')" "required" "diagnostic mentions required"

# ── 4. Missing --root → exit 1 ────────────────────────────────────────────────
echo
echo "=== 4. Missing --root → exit 1 ==="
set +e
ERR=$("$WALLET" state-proof-verify --in "$SINGLE" 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing --root exits 1"
assert_contains "$(echo "$ERR" | tr -d '\r')" "required" "diagnostic mentions required"

# ── 5. --root wrong length → exit 1 ───────────────────────────────────────────
echo
echo "=== 5. --root wrong length → exit 1 ==="
set +e
ERR=$("$WALLET" state-proof-verify --in "$SINGLE" --root "abcd" 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "short --root exits 1"
assert_contains "$(echo "$ERR" | tr -d '\r')" "64 hex" "diagnostic mentions length"

# ── 6. --root non-hex → exit 1 ────────────────────────────────────────────────
echo
echo "=== 6. --root non-hex → exit 1 ==="
NON_HEX="zzzz567890123456789012345678901234567890123456789012345678901234"
set +e
ERR=$("$WALLET" state-proof-verify --in "$SINGLE" --root "$NON_HEX" 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "non-hex --root exits 1"

# ── 7. Unknown flag → exit 1 ──────────────────────────────────────────────────
echo
echo "=== 7. Unknown flag → exit 1 ==="
set +e
ERR=$("$WALLET" state-proof-verify --bogus 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "unknown flag exits 1"
assert_contains "$(echo "$ERR" | tr -d '\r')" "unknown argument" "diagnostic mentions unknown argument"

# ── 8. File not found → exit 1 ────────────────────────────────────────────────
echo
echo "=== 8. File not found → exit 1 ==="
set +e
ERR=$("$WALLET" state-proof-verify --in "$SCRATCH/nope.json" --root "$ROOT_SINGLE" 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing file exits 1"
assert_contains "$(echo "$ERR" | tr -d '\r')" "cannot open" "diagnostic mentions cannot open"

# ── 9. Malformed JSON → exit 1 + malformed_proof ──────────────────────────────
echo
echo "=== 9. Malformed JSON → exit 1 ==="
BADJSON="$SCRATCH/bad.json"
echo 'not { valid json' > "$BADJSON"
set +e
OUT=$("$WALLET" state-proof-verify --in "$BADJSON" --root "$ROOT_SINGLE" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "malformed JSON exits 1"
assert_contains "$(echo "$OUT" | tr -d '\r')" "malformed_proof" "envelope reports malformed_proof"

# ── 10. Missing required field → exit 1 ───────────────────────────────────────
echo
echo "=== 10. Proof missing a required field → exit 1 ==="
MISSING="$SCRATCH/missing.json"
echo '{"key_bytes":"6100","value_hash":"'"$VH_A"'","target_index":0}' > "$MISSING"
set +e
OUT=$("$WALLET" state-proof-verify --in "$MISSING" --root "$ROOT_SINGLE" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing field exits 1"
assert_contains "$(echo "$OUT" | tr -d '\r')" "malformed_proof" "missing field reports malformed_proof"

# ── 11. Proof carrying {"error":...} → exit 1 ─────────────────────────────────
echo
echo "=== 11. Proof error envelope → exit 1 ==="
ERRPROOF="$SCRATCH/errproof.json"
echo '{"error":"not_found"}' > "$ERRPROOF"
set +e
OUT=$("$WALLET" state-proof-verify --in "$ERRPROOF" --root "$ROOT_SINGLE" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "error-envelope proof exits 1"
assert_contains "$(echo "$OUT" | tr -d '\r')" "error field" "diagnostic mentions error field"

# ── 12. Happy path single-leaf VALID → exit 0 ─────────────────────────────────
echo
echo "=== 12. Single-leaf VALID → exit 0 ==="
set +e
OUT=$("$WALLET" state-proof-verify --in "$SINGLE" --root "$ROOT_SINGLE" 2>&1); RC=$?
set -e
assert_eq "$RC" "0" "single-leaf valid proof exits 0"
assert_contains "$(echo "$OUT" | tr -d '\r')" "VALID" "human output reports VALID"

# ── 13. Happy path multi-leaf VALID → exit 0 ──────────────────────────────────
echo
echo "=== 13. Multi-leaf VALID → exit 0 ==="
set +e
OUT=$("$WALLET" state-proof-verify --in "$MULTI" --root "$ROOT_MULTI" 2>&1); RC=$?
set -e
assert_eq "$RC" "0" "multi-leaf valid proof exits 0"
assert_contains "$(echo "$OUT" | tr -d '\r')" "VALID" "multi-leaf human output reports VALID"

# ── 14. --json happy path: strict schema ──────────────────────────────────────
echo
echo "=== 14. --json schema check ==="
set +e
JSON=$("$WALLET" state-proof-verify --in "$MULTI" --root "$ROOT_MULTI" --json 2>&1 | tr -d '\r'); RC=$?
set -e
assert_eq "$RC" "0" "--json valid proof exits 0"
SCHEMA_OK=$(echo "$JSON" | $PY -c "
import sys, json
try:
    d = json.loads(sys.stdin.read())
    assert isinstance(d.get('in'),            str),  'in:str'
    assert isinstance(d.get('root'),          str),  'root:str'
    assert d.get('valid') is True,                   'valid==true'
    assert isinstance(d.get('namespace'),     str),  'namespace:str'
    assert isinstance(d.get('key_bytes'),     str),  'key_bytes:str'
    assert isinstance(d.get('value_hash'),    str),  'value_hash:str'
    assert isinstance(d.get('target_index'),  int),  'target_index:int'
    assert isinstance(d.get('leaf_count'),    int),  'leaf_count:int'
    assert isinstance(d.get('proof_len'),     int),  'proof_len:int'
    assert d.get('root_matches_proof') is True,      'root_matches_proof'
    assert d.get('exit_reason') == 'valid',          'exit_reason==valid'
    print('ok')
except AssertionError as e:
    print('bad:'+str(e))
except Exception as e:
    print('parse:'+str(e))
")
assert_eq "$SCHEMA_OK" "ok" "JSON envelope passes strict schema check"

# ── 15. Wrong --root → exit 2 INVALID ─────────────────────────────────────────
echo
echo "=== 15. Wrong --root → exit 2 INVALID ==="
WRONG_ROOT="0000000000000000000000000000000000000000000000000000000000000000"
set +e
OUT=$("$WALLET" state-proof-verify --in "$MULTI" --root "$WRONG_ROOT" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "2" "wrong root exits 2"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"valid":false' "envelope reports valid=false"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"exit_reason":"invalid"' "exit_reason=invalid"

# ── 16. Tampered value_hash → exit 2 INVALID ──────────────────────────────────
echo
echo "=== 16. Tampered value_hash → exit 2 INVALID ==="
TAMPER="$SCRATCH/tamper.json"
$PY -c "
import json
d = json.load(open('$MULTI'))
d['value_hash'] = '$VH_D'  # wrong value hash for the proven leaf
json.dump(d, open('$TAMPER','w'))
"
set +e
OUT=$("$WALLET" state-proof-verify --in "$TAMPER" --root "$ROOT_MULTI" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "2" "tampered value_hash exits 2"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"valid":false' "tamper reports valid=false"

# ── 17. Proof self state_root disagrees with --root → exit 2 ──────────────────
echo
echo "=== 17. Proof self-root != --root → exit 2 ==="
# Use the multi-leaf proof but pass the SINGLE-leaf root: the merkle walk
# will fail anyway, but also exercise a case where the walk passes but the
# self-root differs. Easiest: rewrite the proof's state_root field to a
# bogus value while keeping the path valid, then verify against the REAL
# root — root_matches_proof must be false → invalid.
SELFMISMATCH="$SCRATCH/selfmismatch.json"
$PY -c "
import json
d = json.load(open('$MULTI'))
d['state_root'] = '$WRONG_ROOT'  # lie about the self-root
json.dump(d, open('$SELFMISMATCH','w'))
"
set +e
OUT=$("$WALLET" state-proof-verify --in "$SELFMISMATCH" --root "$ROOT_MULTI" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "2" "self-root mismatch exits 2"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"root_matches_proof":false' "root_matches_proof=false"

# ── 18. Mixed-case --root still VALID ─────────────────────────────────────────
echo
echo "=== 18. Mixed-case --root normalized → VALID ==="
UPPER_ROOT=$(echo "$ROOT_MULTI" | tr 'a-f' 'A-F')
set +e
OUT=$("$WALLET" state-proof-verify --in "$MULTI" --root "$UPPER_ROOT" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "0" "uppercase root still verifies"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"valid":true' "case-normalized root reports valid=true"

# ── 19. Human output labelled fields ──────────────────────────────────────────
echo
echo "=== 19. Human output ==="
set +e
OUT=$("$WALLET" state-proof-verify --in "$MULTI" --root "$ROOT_MULTI" 2>&1 | tr -d '\r'); RC=$?
set -e
assert_eq "$RC" "0" "human happy path exits 0"
assert_contains "$OUT" "state-proof-verify:" "human output has top header"
assert_contains "$OUT" "leaf_count" "human output prints leaf_count"
assert_contains "$OUT" "result" "human output prints result line"

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo "=== Test summary ==="
echo "  $pass_count pass / $fail_count fail"
if [ "$fail_count" = "0" ]; then
    echo "  PASS: determ-wallet state-proof-verify"; exit 0
else
    echo "  FAIL"; exit 1
fi
