#!/usr/bin/env bash
# determ-wallet verify-stake-unlock CLI test.
#
# Verifies the OFFLINE trustless verifier for an account's stake-unlock
# eligibility — the `s:`-namespace sibling of verify-dapp-registration (d:).
# The command takes an s:-namespace state-proof JSON (the shape returned by the
# `state_proof` RPC), an UNTRUSTED stake-table-row JSON (the stakes-snapshot /
# stake_bulk_query return shape), an operator-supplied 32-byte state_root, and
# a committee-verified head height, then:
#   (a) re-derives the s:-namespace value_hash from the entry's locked +
#       unlock_height (build_state_leaves byte encoding, src/chain/chain.cpp);
#   (b) re-derives key_bytes = "s:" + domain (ASCII);
#   (c) cross-checks both against the proof;
#   (d) Merkle-verifies the proof against the state_root; and
#   (e) computes eligible = (head_height >= unlock_height) — the exact UNSTAKE
#       gate the chain enforces (Chain::apply rejects when head < unlock_height,
#       S-017 producer/validator parity) —
# all entirely in-process (no RPC, no network, no daemon, no subprocess).
# A node that lies about locked / unlock_height produces a value_hash that
# will NOT verify.
#
# Fixtures are generated by an independent Python reference implementation of
# the SAME documented encodings:
#   value_hash = SHA-256( u64_be(locked) || u64_be(unlock_height) )
#   key_bytes  = b"s:" + domain
#   leaf_hash  = SHA-256(0x00 || u32_be(key_len) || key || value_hash)
#   inner_hash = SHA-256(0x01 || left || right)
#   balanced binary tree, sorted by key, duplicate-last to even each odd level.
# So a VALID fixture carries a genuinely-correct root + sibling path + entry,
# and the wallet's verdict is cross-checked against an independent computation.
#
# Covers (~28 assertions):
#   1.  --help text exists + documents every flag.
#   2.  Global help dispatcher does NOT need to list it (curated subset); but
#       the dispatch resolves the command (smoke via --help exit 0).
#   3.  Missing --proof / --entry / --root / --head-height → exit 1.
#   4.  --root wrong length / non-hex → exit 1.
#   5.  Unknown flag → exit 1.
#   6.  File not found (proof / entry) → exit 1.
#   7.  Malformed proof / entry JSON → exit 1 + malformed_proof / _entry.
#   8.  Entry missing a required field → exit 1.
#   9.  Happy path (single-leaf s: tree) VALID + eligible → exit 0.
#  10.  Happy path (multi-leaf, mixed namespaces) VALID → exit 0.
#  11.  --json happy path: strict schema + valid:true + key/value matches.
#  12.  Wrong --root → exit 2 INVALID.
#  13.  Tampered entry field (locked) → value_hash mismatch → exit 2.
#  14.  Entry for a DIFFERENT domain → key mismatch → exit 2.
#  15.  Still-locked entry (head < unlock_height) → VALID but eligible=false
#       + blocks_until_unlock countdown.
#  16.  UINT64_MAX unlock_height (no deregistration pending) → VALID, never
#       eligible, no blocks_until_unlock field.
#  17.  Mixed-case --root still VALID (normalized).
#
# Cluster-free + deterministic. Run from repo root:
#   bash tools/test_wallet_verify_stake_unlock.sh
set -u
cd "$(dirname "$0")/.."
source tools/common.sh

if [ -z "${DETERM_WALLET:-}" ] || [ ! -x "$DETERM_WALLET" ]; then
    echo "  SKIP: determ-wallet binary not found; build with"
    echo "        cmake --build build --config Release --target determ-wallet"
    exit 0
fi

WALLET="$DETERM_WALLET"
SCRATCH="build/test_wallet_verify_stake_unlock.$$"
mkdir -p "$SCRATCH"
trap 'rm -rf "$SCRATCH"' EXIT

PY=python
command -v python >/dev/null 2>&1 || PY=python3

pass_count=0; fail_count=0
assert_eq() {
  if [ "$1" = "$2" ]; then echo "  PASS: $3"; pass_count=$((pass_count + 1))
  else echo "  FAIL: $3"; echo "       expected: $2"; echo "       got:      $1"; fail_count=$((fail_count + 1)); fi
}
assert_contains() {
  if echo "$1" | grep -q -- "$2"; then echo "  PASS: $3"; pass_count=$((pass_count + 1))
  else echo "  FAIL: $3"; echo "       missing substring: $2"; fail_count=$((fail_count + 1)); fi
}

# ── Reference fixture generator (independent s: encoding + Merkle) ────────────
# Emits a matched (proof.json, entry.json) pair for a stake-table row leaf
# embedded in a multi-leaf state tree, and prints the computed root on stdout.
# The implementation MUST match build_state_leaves (src/chain/chain.cpp) +
# crypto::merkle.cpp exactly.
#
# args: <proof_out> <entry_out> <domain> <locked> <unlock_height>
gen_fixture() {
  $PY - "$@" <<'PYEOF'
import sys, json, hashlib, struct

(proof_out, entry_out, domain, locked, unlock_height) = sys.argv[1:6]
locked        = int(locked)
unlock_height = int(unlock_height)

def u64(v): return struct.pack(">Q", v)

# s:-namespace value_hash (build_state_leaves byte-for-byte).
def stake_value_hash():
    h = hashlib.sha256()
    h.update(u64(locked))
    h.update(u64(unlock_height))
    return h.digest()

def leaf_hash(key, vh):
    return hashlib.sha256(b"\x00" + struct.pack(">I", len(key)) + key + vh).digest()

def inner_hash(l, r):
    return hashlib.sha256(b"\x01" + l + r).digest()

# Build a small mixed-namespace tree so the s: leaf sits among siblings.
skey = b"s:" + domain.encode()
svh  = stake_value_hash()
pairs = [
    (b"a:" + b"acct_x", bytes.fromhex("11" * 32)),
    (b"d:" + b"app_y",  bytes.fromhex("22" * 32)),
    (skey,              svh),
    (b"r:" + b"node_z", bytes.fromhex("33" * 32)),
]
pairs.sort(key=lambda p: p[0])
leaf_count = len(pairs)
target_index = next(i for i, (k, _) in enumerate(pairs) if k == skey)

row = [leaf_hash(k, v) for (k, v) in pairs]
idx = target_index
proof = []
while len(row) > 1:
    if len(row) % 2 == 1:
        row.append(row[-1])
    sib = idx + 1 if idx % 2 == 0 else idx - 1
    proof.append(row[sib])
    row = [inner_hash(row[i], row[i+1]) for i in range(0, len(row), 2)]
    idx //= 2
root = row[0]

proof_doc = {
    "state_root":   root.hex(),
    "namespace":    "s",
    "key_bytes":    skey.hex(),
    "value_hash":   svh.hex(),
    "target_index": target_index,
    "leaf_count":   leaf_count,
    "proof":        [h.hex() for h in proof],
    "height":       100,
}
entry_doc = {
    "domain":        domain,
    "locked":        locked,
    "unlock_height": unlock_height,
}
with open(proof_out, "w") as f: json.dump(proof_doc, f)
with open(entry_out, "w") as f: json.dump(entry_doc, f)
print(root.hex())
PYEOF
}

# ── Single-leaf s: fixture (root == leaf_hash, empty proof). ──────────────────
gen_single() {
  $PY - "$@" <<'PYEOF'
import sys, json, hashlib, struct
(proof_out, entry_out) = sys.argv[1:3]
domain = "solo.example"
locked = 500000
unlock_height = 80
def u64(v): return struct.pack(">Q", v)
h = hashlib.sha256()
h.update(u64(locked)); h.update(u64(unlock_height))
svh = h.digest()
skey = b"s:" + domain.encode()
root = hashlib.sha256(b"\x00" + struct.pack(">I", len(skey)) + skey + svh).digest()
proof_doc = {
    "state_root": root.hex(), "namespace": "s", "key_bytes": skey.hex(),
    "value_hash": svh.hex(), "target_index": 0, "leaf_count": 1,
    "proof": [], "height": 100,
}
entry_doc = {"domain": domain, "locked": locked, "unlock_height": unlock_height}
with open(proof_out, "w") as f: json.dump(proof_doc, f)
with open(entry_out, "w") as f: json.dump(entry_doc, f)
print(root.hex())
PYEOF
}

UMAX=18446744073709551615

# Single-leaf, eligible: unlock_height 80, evaluate at head 100 → eligible.
PROOF_S="$SCRATCH/s_proof.json"; ENTRY_S="$SCRATCH/s_entry.json"
ROOT_S=$(gen_single "$PROOF_S" "$ENTRY_S")
echo "  fixture: ROOT_S=$ROOT_S"

# Multi-leaf, eligible at head 100: unlock_height 90.
PROOF_E="$SCRATCH/e_proof.json"; ENTRY_E="$SCRATCH/e_entry.json"
ROOT_E=$(gen_fixture "$PROOF_E" "$ENTRY_E" "exit.example" 1000000 90)
echo "  fixture: ROOT_E=$ROOT_E"

# Multi-leaf, still locked at head 100: unlock_height 150 → 50 blocks to go.
PROOF_L="$SCRATCH/l_proof.json"; ENTRY_L="$SCRATCH/l_entry.json"
ROOT_L=$(gen_fixture "$PROOF_L" "$ENTRY_L" "locked.example" 2000000 150)
echo "  fixture: ROOT_L=$ROOT_L"

# Multi-leaf, no deregistration pending: unlock_height == UINT64_MAX.
PROOF_N="$SCRATCH/n_proof.json"; ENTRY_N="$SCRATCH/n_entry.json"
ROOT_N=$(gen_fixture "$PROOF_N" "$ENTRY_N" "active.example" 3000000 "$UMAX")
echo "  fixture: ROOT_N=$ROOT_N"

# ── 1. --help text ────────────────────────────────────────────────────────────
echo
echo "=== 1. --help text ==="
HELP=$("$WALLET" verify-stake-unlock --help 2>&1 | tr -d '\r')
assert_contains "$HELP" "Usage: determ-wallet verify-stake-unlock" "help shows synopsis"
assert_contains "$HELP" "OFFLINE trustless verifier"               "help describes purpose"
assert_contains "$HELP" "\-\-proof <proof.json>"                   "help documents --proof"
assert_contains "$HELP" "\-\-entry <entry.json>"                   "help documents --entry"
assert_contains "$HELP" "\-\-root <hex64>"                         "help documents --root"
assert_contains "$HELP" "\-\-head-height <H>"                      "help documents --head-height"
assert_contains "$HELP" "\-\-json"                                 "help documents --json"
assert_contains "$HELP" "s:"                                       "help references the s: namespace"

# ── 2. Dispatch resolves the command (exit 0 on --help) ───────────────────────
echo
echo "=== 2. Dispatch resolves verify-stake-unlock ==="
set +e
"$WALLET" verify-stake-unlock --help >/dev/null 2>&1; RC=$?
set -e
assert_eq "$RC" "0" "verify-stake-unlock --help exits 0 (command dispatched)"

# ── 3. Missing required flags → exit 1 ────────────────────────────────────────
echo
echo "=== 3. Missing required flags → exit 1 ==="
set +e
ERR=$("$WALLET" verify-stake-unlock --entry "$ENTRY_E" --root "$ROOT_E" --head-height 100 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing --proof exits 1"
assert_contains "$(echo "$ERR" | tr -d '\r')" "required" "missing --proof mentions required"
set +e
ERR=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --root "$ROOT_E" --head-height 100 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing --entry exits 1"
set +e
ERR=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --entry "$ENTRY_E" --head-height 100 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing --root exits 1"
set +e
ERR=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --entry "$ENTRY_E" --root "$ROOT_E" 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing --head-height exits 1"

# ── 4. --root wrong length / non-hex → exit 1 ─────────────────────────────────
echo
echo "=== 4. --root wrong length / non-hex → exit 1 ==="
set +e
ERR=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --entry "$ENTRY_E" --root "abcd" --head-height 100 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "short --root exits 1"
assert_contains "$(echo "$ERR" | tr -d '\r')" "64 hex" "diagnostic mentions length"
NON_HEX="zzzz567890123456789012345678901234567890123456789012345678901234"
set +e
ERR=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --entry "$ENTRY_E" --root "$NON_HEX" --head-height 100 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "non-hex --root exits 1"

# ── 5. Unknown flag → exit 1 ──────────────────────────────────────────────────
echo
echo "=== 5. Unknown flag → exit 1 ==="
set +e
ERR=$("$WALLET" verify-stake-unlock --bogus 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "unknown flag exits 1"
assert_contains "$(echo "$ERR" | tr -d '\r')" "unknown argument" "diagnostic mentions unknown argument"

# ── 6. File not found → exit 1 ────────────────────────────────────────────────
echo
echo "=== 6. File not found → exit 1 ==="
set +e
ERR=$("$WALLET" verify-stake-unlock --proof "$SCRATCH/nope.json" --entry "$ENTRY_E" --root "$ROOT_E" --head-height 100 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing proof file exits 1"
assert_contains "$(echo "$ERR" | tr -d '\r')" "cannot open" "diagnostic mentions cannot open"
set +e
ERR=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --entry "$SCRATCH/nope.json" --root "$ROOT_E" --head-height 100 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing entry file exits 1"

# ── 7. Malformed JSON → exit 1 ────────────────────────────────────────────────
echo
echo "=== 7. Malformed JSON → exit 1 ==="
BADJSON="$SCRATCH/bad.json"
echo 'not { valid json' > "$BADJSON"
set +e
OUT=$("$WALLET" verify-stake-unlock --proof "$BADJSON" --entry "$ENTRY_E" --root "$ROOT_E" --head-height 100 --json 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "malformed proof JSON exits 1"
assert_contains "$(echo "$OUT" | tr -d '\r')" "malformed_proof" "envelope reports malformed_proof"
set +e
OUT=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --entry "$BADJSON" --root "$ROOT_E" --head-height 100 --json 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "malformed entry JSON exits 1"
assert_contains "$(echo "$OUT" | tr -d '\r')" "malformed_entry" "envelope reports malformed_entry"

# ── 8. Missing required field → exit 1 ────────────────────────────────────────
echo
echo "=== 8. Entry missing a required field → exit 1 ==="
MISSING="$SCRATCH/missing_entry.json"
echo '{"domain":"x.example","locked":100}' > "$MISSING"
set +e
OUT=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --entry "$MISSING" --root "$ROOT_E" --head-height 100 --json 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "entry missing unlock_height exits 1"
assert_contains "$(echo "$OUT" | tr -d '\r')" "malformed_entry" "missing field reports malformed_entry"

# ── 9. Happy path single-leaf VALID + eligible → exit 0 ───────────────────────
echo
echo "=== 9. Single-leaf VALID + eligible → exit 0 ==="
set +e
OUT=$("$WALLET" verify-stake-unlock --proof "$PROOF_S" --entry "$ENTRY_S" --root "$ROOT_S" --head-height 100 2>&1 | tr -d '\r'); RC=$?
set -e
assert_eq "$RC" "0" "single-leaf valid stake row exits 0"
assert_contains "$OUT" "VALID"             "human output reports VALID"
assert_contains "$OUT" "eligible          : true" "single-leaf head>=unlock reports eligible=true"

# ── 10. Happy path multi-leaf VALID → exit 0 ──────────────────────────────────
echo
echo "=== 10. Multi-leaf VALID → exit 0 ==="
set +e
OUT=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --entry "$ENTRY_E" --root "$ROOT_E" --head-height 100 2>&1 | tr -d '\r'); RC=$?
set -e
assert_eq "$RC" "0" "multi-leaf valid stake row exits 0"
assert_contains "$OUT" "VALID" "multi-leaf human output reports VALID"

# ── 11. --json happy path: strict schema ──────────────────────────────────────
echo
echo "=== 11. --json schema check ==="
set +e
JSON=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --entry "$ENTRY_E" --root "$ROOT_E" --head-height 100 --json 2>&1 | tr -d '\r'); RC=$?
set -e
assert_eq "$RC" "0" "--json valid stake row exits 0"
SCHEMA_OK=$(echo "$JSON" | $PY -c "
import sys, json
try:
    d = json.loads(sys.stdin.read())
    assert isinstance(d.get('proof'),              str),  'proof:str'
    assert isinstance(d.get('entry'),              str),  'entry:str'
    assert isinstance(d.get('root'),               str),  'root:str'
    assert isinstance(d.get('head_height'),        int),  'head_height:int'
    assert d.get('valid') is True,                        'valid==true'
    assert d.get('domain') == 'exit.example',             'domain'
    assert isinstance(d.get('namespace'),          str),  'namespace:str'
    assert isinstance(d.get('key_bytes'),          str),  'key_bytes:str'
    assert isinstance(d.get('expected_key_bytes'), str),  'expected_key_bytes:str'
    assert d.get('key_matches') is True,                  'key_matches'
    assert isinstance(d.get('value_hash'),         str),  'value_hash:str'
    assert isinstance(d.get('derived_value_hash'), str),  'derived_value_hash:str'
    assert d.get('value_hash_matches') is True,           'value_hash_matches'
    assert isinstance(d.get('target_index'),       int),  'target_index:int'
    assert isinstance(d.get('leaf_count'),         int),  'leaf_count:int'
    assert isinstance(d.get('proof_len'),          int),  'proof_len:int'
    assert d.get('root_matches_proof') is True,           'root_matches_proof'
    assert isinstance(d.get('locked'),             int),  'locked:int'
    assert isinstance(d.get('unlock_height'),      int),  'unlock_height:int'
    assert d.get('unlock_pending') is True,               'unlock_pending'
    assert d.get('eligible') is True,                     'eligible (head 100 >= unlock 90)'
    assert d.get('exit_reason') == 'valid',               'exit_reason==valid'
    assert d.get('value_hash') == d.get('derived_value_hash'), 'vh==derived'
    print('ok')
except AssertionError as e:
    print('bad:'+str(e))
except Exception as e:
    print('parse:'+str(e))
")
assert_eq "$SCHEMA_OK" "ok" "JSON envelope passes strict schema check"

# ── 12. Wrong --root → exit 2 INVALID ─────────────────────────────────────────
echo
echo "=== 12. Wrong --root → exit 2 INVALID ==="
WRONG_ROOT="0000000000000000000000000000000000000000000000000000000000000000"
set +e
OUT=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --entry "$ENTRY_E" --root "$WRONG_ROOT" --head-height 100 --json 2>&1); RC=$?
set -e
assert_eq "$RC" "2" "wrong root exits 2"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"valid":false'           "envelope reports valid=false"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"exit_reason":"invalid"' "exit_reason=invalid"

# ── 13. Tampered entry field → value_hash mismatch → exit 2 ───────────────────
echo
echo "=== 13. Tampered entry (locked) → value_hash mismatch → exit 2 ==="
TAMPER="$SCRATCH/tamper_entry.json"
$PY -c "
import json
d = json.load(open('$ENTRY_E'))
d['locked'] = 999999999  # lie about the locked amount
json.dump(d, open('$TAMPER','w'))
"
set +e
OUT=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --entry "$TAMPER" --root "$ROOT_E" --head-height 100 --json 2>&1); RC=$?
set -e
assert_eq "$RC" "2" "tampered locked exits 2"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"value_hash_matches":false' "tamper reports value_hash_matches=false"

# ── 14. Entry for a different domain → key mismatch → exit 2 ───────────────────
echo
echo "=== 14. Wrong-domain entry → key mismatch → exit 2 ==="
WRONGDOM="$SCRATCH/wrongdom_entry.json"
$PY -c "
import json
d = json.load(open('$ENTRY_E'))
d['domain'] = 'someone-else.example'  # the proof is for exit.example
json.dump(d, open('$WRONGDOM','w'))
"
set +e
OUT=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --entry "$WRONGDOM" --root "$ROOT_E" --head-height 100 --json 2>&1); RC=$?
set -e
assert_eq "$RC" "2" "wrong-domain entry exits 2"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"key_matches":false' "wrong domain reports key_matches=false"

# ── 15. Still-locked entry → VALID but eligible=false + countdown ─────────────
echo
echo "=== 15. Still-locked entry → VALID + eligible=false + countdown ==="
set +e
OUT=$("$WALLET" verify-stake-unlock --proof "$PROOF_L" --entry "$ENTRY_L" --root "$ROOT_L" --head-height 100 --json 2>&1); RC=$?
set -e
assert_eq "$RC" "0" "still-locked-but-committed stake still VALID (exit 0)"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"valid":true'     "still-locked entry valid=true"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"eligible":false' "head 100 < unlock 150 reports eligible=false"
# unlock_height 150 - head 100 = 50 blocks to go.
assert_contains "$(echo "$OUT" | tr -d '\r')" '"blocks_until_unlock":50' "countdown reports 50 blocks_until_unlock"

# ── 16. UINT64_MAX unlock_height → VALID, never eligible, no countdown ────────
echo
echo "=== 16. No-deregistration-pending (UINT64_MAX) → VALID + eligible=false ==="
set +e
OUT=$("$WALLET" verify-stake-unlock --proof "$PROOF_N" --entry "$ENTRY_N" --root "$ROOT_N" --head-height 100 --json 2>&1); RC=$?
set -e
assert_eq "$RC" "0" "active-registrant stake still VALID (exit 0)"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"unlock_pending":false' "UINT64_MAX reports unlock_pending=false"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"eligible":false'       "active registrant never eligible"
NO_COUNTDOWN=$(echo "$OUT" | tr -d '\r' | $PY -c "
import sys, json
d = json.loads(sys.stdin.read())
print('absent' if 'blocks_until_unlock' not in d else 'present')
")
assert_eq "$NO_COUNTDOWN" "absent" "no blocks_until_unlock field when unlock_pending=false"

# ── 17. Mixed-case --root still VALID ─────────────────────────────────────────
echo
echo "=== 17. Mixed-case --root normalized → VALID ==="
UPPER_ROOT=$(echo "$ROOT_E" | tr 'a-f' 'A-F')
set +e
OUT=$("$WALLET" verify-stake-unlock --proof "$PROOF_E" --entry "$ENTRY_E" --root "$UPPER_ROOT" --head-height 100 --json 2>&1); RC=$?
set -e
assert_eq "$RC" "0" "uppercase root still verifies"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"valid":true' "case-normalized root reports valid=true"

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo "=== Test summary ==="
echo "  $pass_count pass / $fail_count fail"
if [ "$fail_count" = "0" ]; then
    echo "  PASS: determ-wallet verify-stake-unlock"; exit 0
else
    echo "  FAIL"; exit 1
fi
