#!/usr/bin/env bash
# determ-wallet verify-dapp-registration CLI test.
#
# Verifies the OFFLINE trustless verifier for a v2.18 DAPP_REGISTER on-chain
# registration — the `d:`-namespace sibling of the i:/m:/p: composite-key
# readers. The command takes a d:-namespace state-proof JSON (the shape
# returned by the `state_proof` RPC), an UNTRUSTED registry-entry JSON (the
# `dapp_info` RPC return shape), and an operator-supplied 32-byte state_root,
# then:
#   (a) re-derives the d:-namespace value_hash from the entry's claimed fields
#       (build_state_leaves byte encoding, src/chain/chain.cpp);
#   (b) re-derives key_bytes = "d:" + domain (ASCII);
#   (c) cross-checks both against the proof; and
#   (d) Merkle-verifies the proof against the state_root —
# all entirely in-process (no RPC, no network, no daemon, no subprocess).
# A node that lies about ANY registration field produces a value_hash that
# will NOT verify.
#
# Fixtures are generated by an independent Python reference implementation of
# the SAME documented encodings:
#   value_hash = SHA-256( service_pubkey[32]
#                       || u64_be(registered_at) || u64_be(active_from)
#                       || u64_be(inactive_from)
#                       || u64_be(len(endpoint_url)) || endpoint_url
#                       || u64_be(len(topics)) [ u64_be(len(t)) || t ]...
#                       || u64_be(retention)
#                       || u64_be(len(metadata)) || metadata )
#   key_bytes  = b"d:" + domain
#   leaf_hash  = SHA-256(0x00 || u32_be(key_len) || key || value_hash)
#   inner_hash = SHA-256(0x01 || left || right)
#   balanced binary tree, sorted by key, duplicate-last to even each odd level.
# So a VALID fixture carries a genuinely-correct root + sibling path + entry,
# and the wallet's verdict is cross-checked against an independent computation.
#
# Covers (~30 assertions):
#   1.  --help text exists + documents every flag.
#   2.  Global help dispatcher lists verify-dapp-registration.
#   3.  Missing --proof / --entry / --root → exit 1.
#   4.  --root wrong length / non-hex → exit 1.
#   5.  Unknown flag → exit 1.
#   6.  File not found (proof / entry) → exit 1.
#   7.  Malformed proof / entry JSON → exit 1 + malformed_proof / _entry.
#   8.  Proof / entry missing a required field → exit 1.
#   9.  Happy path (single-leaf d: tree) VALID → exit 0, activation=registered.
#  10.  Happy path (multi-leaf, mixed namespaces) VALID → exit 0.
#  11.  --json happy path: strict schema + valid:true + key/value matches.
#  12.  Wrong --root → exit 2 INVALID.
#  13.  Tampered entry field (endpoint_url) → value_hash mismatch → exit 2.
#  14.  Entry for a DIFFERENT domain → key mismatch → exit 2.
#  15.  Deactivated entry (inactive_from <= height) → VALID but activation=inactive.
#  16.  Pending entry (active_from > height) → VALID but activation=pending.
#  17.  Mixed-case --root + value_hash still VALID (normalized).
#
# Cluster-free + deterministic. Run from repo root:
#   bash tools/test_wallet_verify_dapp_registration.sh
set -u
cd "$(dirname "$0")/.."
source tools/common.sh

if [ -z "${DETERM_WALLET:-}" ] || [ ! -x "$DETERM_WALLET" ]; then
    echo "  SKIP: determ-wallet binary not found; build with"
    echo "        cmake --build build --config Release --target determ-wallet"
    exit 0
fi

WALLET="$DETERM_WALLET"
SCRATCH="build/test_wallet_verify_dapp_registration.$$"
mkdir -p "$SCRATCH"
trap 'rm -rf "$SCRATCH"' EXIT

PY=python
command -v python >/dev/null 2>&1 || PY=python3

pass_count=0; fail_count=0
assert_eq() {
  if [ "$1" = "$2" ]; then echo "  PASS: $3"; pass_count=$((pass_count + 1))
  else echo "  FAIL: $3"; echo "       expected: $2"; echo "       got:      $1"; fail_count=$((fail_count + 1)); fi
}
assert_contains() {
  if echo "$1" | grep -q -- "$2"; then echo "  PASS: $3"; pass_count=$((pass_count + 1))
  else echo "  FAIL: $3"; echo "       missing substring: $2"; fail_count=$((fail_count + 1)); fi
}

# ── Reference fixture generator (independent d: encoding + Merkle) ────────────
# Emits a matched (proof.json, entry.json) pair for a DApp registration leaf
# embedded in a multi-leaf state tree, and prints the computed root on stdout.
# The implementation MUST match build_state_leaves (src/chain/chain.cpp) +
# crypto::merkle.cpp exactly.
#
# args: <proof_out> <entry_out> <domain> <endpoint> <topics_csv> <retention>
#       <metadata_hex> <registered_at> <active_from> <inactive_from> <height>
gen_fixture() {
  $PY - "$@" <<'PYEOF'
import sys, json, hashlib, struct

(proof_out, entry_out, domain, endpoint, topics_csv, retention,
 metadata_hex, registered_at, active_from, inactive_from, height) = sys.argv[1:12]
retention      = int(retention)
registered_at  = int(registered_at)
active_from    = int(active_from)
inactive_from  = int(inactive_from)
height         = int(height)
topics = [t for t in topics_csv.split(",") if t != ""]
service_pubkey = bytes.fromhex("aa" * 32)
metadata = bytes.fromhex(metadata_hex) if metadata_hex else b""

def u64(v): return struct.pack(">Q", v)

# d:-namespace value_hash (build_state_leaves byte-for-byte).
def dapp_value_hash():
    h = hashlib.sha256()
    h.update(service_pubkey)
    h.update(u64(registered_at))
    h.update(u64(active_from))
    h.update(u64(inactive_from))
    eb = endpoint.encode()
    h.update(u64(len(eb))); h.update(eb)
    h.update(u64(len(topics)))
    for t in topics:
        tb = t.encode()
        h.update(u64(len(tb))); h.update(tb)
    h.update(u64(retention))
    h.update(u64(len(metadata))); h.update(metadata)
    return h.digest()

def leaf_hash(key, vh):
    return hashlib.sha256(b"\x00" + struct.pack(">I", len(key)) + key + vh).digest()

def inner_hash(l, r):
    return hashlib.sha256(b"\x01" + l + r).digest()

# Build a small mixed-namespace tree so the d: leaf sits among siblings.
dkey = b"d:" + domain.encode()
dvh  = dapp_value_hash()
pairs = [
    (b"a:" + b"acct_x", bytes.fromhex("11" * 32)),
    (dkey,              dvh),
    (b"s:" + b"node_y", bytes.fromhex("22" * 32)),
    (b"r:" + b"node_z", bytes.fromhex("33" * 32)),
]
pairs.sort(key=lambda p: p[0])
leaf_count = len(pairs)
target_index = next(i for i, (k, _) in enumerate(pairs) if k == dkey)

row = [leaf_hash(k, v) for (k, v) in pairs]
idx = target_index
proof = []
while len(row) > 1:
    if len(row) % 2 == 1:
        row.append(row[-1])
    sib = idx + 1 if idx % 2 == 0 else idx - 1
    proof.append(row[sib])
    row = [inner_hash(row[i], row[i+1]) for i in range(0, len(row), 2)]
    idx //= 2
root = row[0]

proof_doc = {
    "state_root":   root.hex(),
    "namespace":    "d",
    "key_bytes":    dkey.hex(),
    "value_hash":   dvh.hex(),
    "target_index": target_index,
    "leaf_count":   leaf_count,
    "proof":        [h.hex() for h in proof],
    "height":       height,
}
entry_doc = {
    "domain":         domain,
    "service_pubkey": service_pubkey.hex(),
    "endpoint_url":   endpoint,
    "topics":         topics,
    "retention":      retention,
    "metadata":       metadata.hex(),
    "registered_at":  registered_at,
    "active_from":    active_from,
    "inactive_from":  inactive_from,
    "height":         height,
}
with open(proof_out, "w") as f: json.dump(proof_doc, f)
with open(entry_out, "w") as f: json.dump(entry_doc, f)
print(root.hex())
PYEOF
}

# ── Single-leaf d: fixture (root == leaf_hash, empty proof). ──────────────────
# A degenerate one-leaf tree whose only leaf is the DApp registration.
gen_single() {
  $PY - "$@" <<'PYEOF'
import sys, json, hashlib, struct
(proof_out, entry_out) = sys.argv[1:3]
domain = "solo.example"
service_pubkey = bytes.fromhex("aa" * 32)
def u64(v): return struct.pack(">Q", v)
h = hashlib.sha256()
h.update(service_pubkey)
h.update(u64(5)); h.update(u64(6)); h.update(u64(2**64 - 1))
eb = b"https://solo"
h.update(u64(len(eb))); h.update(eb)
h.update(u64(0))               # no topics
h.update(u64(0))               # retention
h.update(u64(0))               # empty metadata
dvh = h.digest()
dkey = b"d:" + domain.encode()
root = hashlib.sha256(b"\x00" + struct.pack(">I", len(dkey)) + dkey + dvh).digest()
proof_doc = {
    "state_root": root.hex(), "namespace": "d", "key_bytes": dkey.hex(),
    "value_hash": dvh.hex(), "target_index": 0, "leaf_count": 1,
    "proof": [], "height": 10,
}
entry_doc = {
    "domain": domain, "service_pubkey": service_pubkey.hex(),
    "endpoint_url": "https://solo", "topics": [], "retention": 0,
    "metadata": "", "registered_at": 5, "active_from": 6,
    "inactive_from": 18446744073709551615, "height": 10,
}
with open(proof_out, "w") as f: json.dump(proof_doc, f)
with open(entry_out, "w") as f: json.dump(entry_doc, f)
print(root.hex())
PYEOF
}

# Multi-leaf, active registration: active_from <= height < inactive_from.
PROOF_M="$SCRATCH/m_proof.json"; ENTRY_M="$SCRATCH/m_entry.json"
ROOT_M=$(gen_fixture "$PROOF_M" "$ENTRY_M" "chat.example" "https://chat" "chat,rpc" 0 "deadbeef" 7 8 18446744073709551615 50)
echo "  fixture: ROOT_M=$ROOT_M"

# Single-leaf active registration.
PROOF_S="$SCRATCH/s_proof.json"; ENTRY_S="$SCRATCH/s_entry.json"
ROOT_S=$(gen_single "$PROOF_S" "$ENTRY_S")
echo "  fixture: ROOT_S=$ROOT_S"

# Deactivated registration: inactive_from (40) <= height (50) → activation=inactive.
PROOF_D="$SCRATCH/d_proof.json"; ENTRY_D="$SCRATCH/d_entry.json"
ROOT_D=$(gen_fixture "$PROOF_D" "$ENTRY_D" "gone.example" "https://gone" "rpc" 1 "" 7 8 40 50)
echo "  fixture: ROOT_D=$ROOT_D"

# Pending registration: active_from (90) > height (50) → activation=pending.
PROOF_P="$SCRATCH/p_proof.json"; ENTRY_P="$SCRATCH/p_entry.json"
ROOT_P=$(gen_fixture "$PROOF_P" "$ENTRY_P" "soon.example" "https://soon" "chat" 0 "00ff" 49 90 18446744073709551615 50)
echo "  fixture: ROOT_P=$ROOT_P"

# ── 1. --help text ────────────────────────────────────────────────────────────
echo
echo "=== 1. --help text ==="
HELP=$("$WALLET" verify-dapp-registration --help 2>&1 | tr -d '\r')
assert_contains "$HELP" "Usage: determ-wallet verify-dapp-registration" "help shows synopsis"
assert_contains "$HELP" "OFFLINE trustless verifier"                    "help describes purpose"
assert_contains "$HELP" "\-\-proof <proof.json>"                        "help documents --proof"
assert_contains "$HELP" "\-\-entry <entry.json>"                        "help documents --entry"
assert_contains "$HELP" "\-\-root <hex64>"                              "help documents --root"
assert_contains "$HELP" "\-\-json"                                      "help documents --json"
assert_contains "$HELP" "d:"                                            "help references the d: namespace"

# ── 2. Global help dispatcher ─────────────────────────────────────────────────
echo
echo "=== 2. Global help mentions verify-dapp-registration ==="
GLOBAL=$("$WALLET" help 2>&1 | tr -d '\r')
assert_contains "$GLOBAL" "verify-dapp-registration" "global help lists verify-dapp-registration"

# ── 3. Missing required flags → exit 1 ────────────────────────────────────────
echo
echo "=== 3. Missing required flags → exit 1 ==="
set +e
ERR=$("$WALLET" verify-dapp-registration --entry "$ENTRY_M" --root "$ROOT_M" 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing --proof exits 1"
assert_contains "$(echo "$ERR" | tr -d '\r')" "required" "missing --proof mentions required"
set +e
ERR=$("$WALLET" verify-dapp-registration --proof "$PROOF_M" --root "$ROOT_M" 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing --entry exits 1"
set +e
ERR=$("$WALLET" verify-dapp-registration --proof "$PROOF_M" --entry "$ENTRY_M" 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing --root exits 1"

# ── 4. --root wrong length / non-hex → exit 1 ─────────────────────────────────
echo
echo "=== 4. --root wrong length / non-hex → exit 1 ==="
set +e
ERR=$("$WALLET" verify-dapp-registration --proof "$PROOF_M" --entry "$ENTRY_M" --root "abcd" 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "short --root exits 1"
assert_contains "$(echo "$ERR" | tr -d '\r')" "64 hex" "diagnostic mentions length"
NON_HEX="zzzz567890123456789012345678901234567890123456789012345678901234"
set +e
ERR=$("$WALLET" verify-dapp-registration --proof "$PROOF_M" --entry "$ENTRY_M" --root "$NON_HEX" 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "non-hex --root exits 1"

# ── 5. Unknown flag → exit 1 ──────────────────────────────────────────────────
echo
echo "=== 5. Unknown flag → exit 1 ==="
set +e
ERR=$("$WALLET" verify-dapp-registration --bogus 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "unknown flag exits 1"
assert_contains "$(echo "$ERR" | tr -d '\r')" "unknown argument" "diagnostic mentions unknown argument"

# ── 6. File not found → exit 1 ────────────────────────────────────────────────
echo
echo "=== 6. File not found → exit 1 ==="
set +e
ERR=$("$WALLET" verify-dapp-registration --proof "$SCRATCH/nope.json" --entry "$ENTRY_M" --root "$ROOT_M" 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing proof file exits 1"
assert_contains "$(echo "$ERR" | tr -d '\r')" "cannot open" "diagnostic mentions cannot open"
set +e
ERR=$("$WALLET" verify-dapp-registration --proof "$PROOF_M" --entry "$SCRATCH/nope.json" --root "$ROOT_M" 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "missing entry file exits 1"

# ── 7. Malformed JSON → exit 1 ────────────────────────────────────────────────
echo
echo "=== 7. Malformed JSON → exit 1 ==="
BADJSON="$SCRATCH/bad.json"
echo 'not { valid json' > "$BADJSON"
set +e
OUT=$("$WALLET" verify-dapp-registration --proof "$BADJSON" --entry "$ENTRY_M" --root "$ROOT_M" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "malformed proof JSON exits 1"
assert_contains "$(echo "$OUT" | tr -d '\r')" "malformed_proof" "envelope reports malformed_proof"
set +e
OUT=$("$WALLET" verify-dapp-registration --proof "$PROOF_M" --entry "$BADJSON" --root "$ROOT_M" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "malformed entry JSON exits 1"
assert_contains "$(echo "$OUT" | tr -d '\r')" "malformed_entry" "envelope reports malformed_entry"

# ── 8. Missing required field → exit 1 ────────────────────────────────────────
echo
echo "=== 8. Entry missing a required field → exit 1 ==="
MISSING="$SCRATCH/missing_entry.json"
echo '{"domain":"x.example","service_pubkey":"'"$(printf 'aa%.0s' $(seq 1 32))"'"}' > "$MISSING"
set +e
OUT=$("$WALLET" verify-dapp-registration --proof "$PROOF_M" --entry "$MISSING" --root "$ROOT_M" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "1" "entry missing field exits 1"
assert_contains "$(echo "$OUT" | tr -d '\r')" "malformed_entry" "missing field reports malformed_entry"

# ── 9. Happy path single-leaf VALID → exit 0 ──────────────────────────────────
echo
echo "=== 9. Single-leaf VALID → exit 0 ==="
set +e
OUT=$("$WALLET" verify-dapp-registration --proof "$PROOF_S" --entry "$ENTRY_S" --root "$ROOT_S" 2>&1 | tr -d '\r'); RC=$?
set -e
assert_eq "$RC" "0" "single-leaf valid registration exits 0"
assert_contains "$OUT" "VALID"      "human output reports VALID"
assert_contains "$OUT" "registered" "single-leaf active entry reports activation=registered"

# ── 10. Happy path multi-leaf VALID → exit 0 ──────────────────────────────────
echo
echo "=== 10. Multi-leaf VALID → exit 0 ==="
set +e
OUT=$("$WALLET" verify-dapp-registration --proof "$PROOF_M" --entry "$ENTRY_M" --root "$ROOT_M" 2>&1 | tr -d '\r'); RC=$?
set -e
assert_eq "$RC" "0" "multi-leaf valid registration exits 0"
assert_contains "$OUT" "VALID" "multi-leaf human output reports VALID"

# ── 11. --json happy path: strict schema ──────────────────────────────────────
echo
echo "=== 11. --json schema check ==="
set +e
JSON=$("$WALLET" verify-dapp-registration --proof "$PROOF_M" --entry "$ENTRY_M" --root "$ROOT_M" --json 2>&1 | tr -d '\r'); RC=$?
set -e
assert_eq "$RC" "0" "--json valid registration exits 0"
SCHEMA_OK=$(echo "$JSON" | $PY -c "
import sys, json
try:
    d = json.loads(sys.stdin.read())
    assert isinstance(d.get('proof'),              str),  'proof:str'
    assert isinstance(d.get('entry'),              str),  'entry:str'
    assert isinstance(d.get('root'),               str),  'root:str'
    assert d.get('valid') is True,                        'valid==true'
    assert d.get('domain') == 'chat.example',             'domain'
    assert isinstance(d.get('namespace'),          str),  'namespace:str'
    assert isinstance(d.get('key_bytes'),          str),  'key_bytes:str'
    assert isinstance(d.get('expected_key_bytes'), str),  'expected_key_bytes:str'
    assert d.get('key_matches') is True,                  'key_matches'
    assert isinstance(d.get('value_hash'),         str),  'value_hash:str'
    assert isinstance(d.get('derived_value_hash'), str),  'derived_value_hash:str'
    assert d.get('value_hash_matches') is True,           'value_hash_matches'
    assert isinstance(d.get('target_index'),       int),  'target_index:int'
    assert isinstance(d.get('leaf_count'),         int),  'leaf_count:int'
    assert isinstance(d.get('proof_len'),          int),  'proof_len:int'
    assert d.get('root_matches_proof') is True,           'root_matches_proof'
    assert d.get('activation') == 'registered',           'activation==registered'
    assert d.get('exit_reason') == 'valid',               'exit_reason==valid'
    assert d.get('value_hash') == d.get('derived_value_hash'), 'vh==derived'
    print('ok')
except AssertionError as e:
    print('bad:'+str(e))
except Exception as e:
    print('parse:'+str(e))
")
assert_eq "$SCHEMA_OK" "ok" "JSON envelope passes strict schema check"

# ── 12. Wrong --root → exit 2 INVALID ─────────────────────────────────────────
echo
echo "=== 12. Wrong --root → exit 2 INVALID ==="
WRONG_ROOT="0000000000000000000000000000000000000000000000000000000000000000"
set +e
OUT=$("$WALLET" verify-dapp-registration --proof "$PROOF_M" --entry "$ENTRY_M" --root "$WRONG_ROOT" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "2" "wrong root exits 2"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"valid":false'           "envelope reports valid=false"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"exit_reason":"invalid"' "exit_reason=invalid"

# ── 13. Tampered entry field → value_hash mismatch → exit 2 ───────────────────
echo
echo "=== 13. Tampered entry (endpoint_url) → value_hash mismatch → exit 2 ==="
TAMPER="$SCRATCH/tamper_entry.json"
$PY -c "
import json
d = json.load(open('$ENTRY_M'))
d['endpoint_url'] = 'https://attacker'  # lie about the endpoint
json.dump(d, open('$TAMPER','w'))
"
set +e
OUT=$("$WALLET" verify-dapp-registration --proof "$PROOF_M" --entry "$TAMPER" --root "$ROOT_M" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "2" "tampered endpoint_url exits 2"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"value_hash_matches":false' "tamper reports value_hash_matches=false"

# ── 14. Entry for a different domain → key mismatch → exit 2 ───────────────────
echo
echo "=== 14. Wrong-domain entry → key mismatch → exit 2 ==="
WRONGDOM="$SCRATCH/wrongdom_entry.json"
$PY -c "
import json
d = json.load(open('$ENTRY_M'))
d['domain'] = 'someone-else.example'  # the proof is for chat.example
json.dump(d, open('$WRONGDOM','w'))
"
set +e
OUT=$("$WALLET" verify-dapp-registration --proof "$PROOF_M" --entry "$WRONGDOM" --root "$ROOT_M" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "2" "wrong-domain entry exits 2"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"key_matches":false' "wrong domain reports key_matches=false"

# ── 15. Deactivated entry → VALID but activation=inactive ─────────────────────
echo
echo "=== 15. Deactivated entry → VALID + activation=inactive ==="
set +e
OUT=$("$WALLET" verify-dapp-registration --proof "$PROOF_D" --entry "$ENTRY_D" --root "$ROOT_D" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "0" "deactivated-but-committed entry still VALID (exit 0)"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"activation":"inactive"' "deactivated entry reports activation=inactive"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"valid":true' "deactivated entry valid=true"

# ── 16. Pending entry → VALID but activation=pending ──────────────────────────
echo
echo "=== 16. Pending entry → VALID + activation=pending ==="
set +e
OUT=$("$WALLET" verify-dapp-registration --proof "$PROOF_P" --entry "$ENTRY_P" --root "$ROOT_P" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "0" "pending-but-committed entry still VALID (exit 0)"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"activation":"pending"' "pending entry reports activation=pending"

# ── 17. Mixed-case --root + value_hash still VALID ────────────────────────────
echo
echo "=== 17. Mixed-case --root normalized → VALID ==="
UPPER_ROOT=$(echo "$ROOT_M" | tr 'a-f' 'A-F')
set +e
OUT=$("$WALLET" verify-dapp-registration --proof "$PROOF_M" --entry "$ENTRY_M" --root "$UPPER_ROOT" --json 2>&1); RC=$?
set -e
assert_eq "$RC" "0" "uppercase root still verifies"
assert_contains "$(echo "$OUT" | tr -d '\r')" '"valid":true' "case-normalized root reports valid=true"

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo "=== Test summary ==="
echo "  $pass_count pass / $fail_count fail"
if [ "$fail_count" = "0" ]; then
    echo "  PASS: determ-wallet verify-dapp-registration"; exit 0
else
    echo "  FAIL"; exit 1
fi
