#!/usr/bin/env bash
# v2.10 Phase 0 / CRYPTO-C99-SPEC §3.6 — the libsodium-free C99 Argon2id (RFC 9106)
# at src/crypto/argon2/argon2id.c, the memory-hard password hash built on the C99
# BLAKE2b. The intended consumer is the passphrase keyfile KDF (today libsodium
# crypto_pwhash); this is the drop-in replacement.
#
# This wrapper runs `determ test-argon2id-c99`, which pins reference vectors
# generated by libsodium crypto_pwhash_argon2id (opslimit=t_cost, memlimit=m_cost*1024,
# p=1, v1.3) -- an independent oracle -- plus determinism / salt-sensitivity / param
# errors. The determ daemon itself does NOT link libsodium (that is the point of the
# libsodium-free stack), so the vectors are captured + pinned rather than computed
# live here. The LIVE byte-equal cross-validation over a t×m grid (12/12) was run by
# gcc-linking the build tree's libsodium.a; to reproduce:
#   SODINC=build/_deps/sodium-src/libsodium/src/libsodium/include
#   gcc -I include -I "$SODINC" <harness> src/crypto/argon2/argon2id.c \
#       src/crypto/blake2/blake2b.c src/crypto/secure_zero.c \
#       build/_deps/sodium-build/libsodium.a -lpthread -o /tmp/a2 && /tmp/a2
set -u
cd "$(dirname "$0")/.."
source tools/common.sh

echo "=== C99 Argon2id (RFC 9106) vs libsodium crypto_pwhash_argon2id reference vectors ==="
OUT=$($DETERM test-argon2id-c99 2>&1)
echo "$OUT"

if echo "$OUT" | tail -3 | grep -q "PASS: argon2id-c99 all libsodium crypto_pwhash_argon2id KATs matched"; then
  echo ""
  echo "  PASS: argon2id-c99 unit test"
  exit 0
else
  echo ""
  echo "  FAIL: argon2id-c99 had assertion failures"
  exit 1
fi
