#!/usr/bin/env python3
"""verify_mldsa_vectors.py — module-local reproducibility gate + generator for
tools/vectors/mldsa_ntt.json (the Determ C99 ML-DSA / Dilithium NTT layer,
CRYPTO-C99-SPEC §3.18).

Independent oracle: a from-scratch reference implementation of the FIPS 204 /
Dilithium negacyclic NTT over Z_q[X]/(X^256+1), q = 8380417, with the twiddle
factors DERIVED here from zeta = 1753 (never copied from the C), PLUS a
schoolbook negacyclic-convolution second oracle — so a stored vector is checked
two independent ways: (1) recompute the fast NTT and match `ntt_out` exactly
(int32-for-int32, the interop gate the C must reproduce), and (2) recompute the
ring product by O(n^2) schoolbook and match `prod` (mod q), which pins the NTT's
mathematical correctness without trusting the fast transform.

Usage:
  python tools/verify_mldsa_vectors.py            # verify the stored corpus
  python tools/verify_mldsa_vectors.py --emit     # (re)generate then verify
Prints "mldsa ntt vectors: N/N OK"; needs only the Python stdlib.
"""
import json, os, sys, random

Q = 8380417
N = 256
MONT = (1 << 32) % Q                    # 2^32 mod q
QINV = pow(Q, -1, 1 << 32)              # q^{-1} mod 2^32 (== 58728449)
ROOT = 1753                             # primitive 512-th root of unity mod q
F = (MONT * MONT % Q) * pow(N, -1, Q) % Q   # mont^2 / 256 (mod q)

def brv8(i):
    return int('{:08b}'.format(i)[::-1], 2)

def smod(x):
    x %= Q
    return x - Q if x > Q // 2 else x

ZETAS = [smod(MONT * pow(ROOT, brv8(i), Q) % Q) for i in range(N)]

def montgomery_reduce(a):
    t = ((a & 0xFFFFFFFF) * QINV) & 0xFFFFFFFF
    if t >= (1 << 31):
        t -= (1 << 32)
    return (a - t * Q) >> 32

def ntt(p):
    p = p[:]
    k = 0
    length = 128
    while length >= 1:
        start = 0
        while start < N:
            k += 1
            z = ZETAS[k]
            for j in range(start, start + length):
                t = montgomery_reduce(z * p[j + length])
                p[j + length] = p[j] - t
                p[j] = p[j] + t
            start += 2 * length
        length >>= 1
    return p

def invntt_tomont(p):
    p = p[:]
    k = 256
    length = 1
    while length < N:
        start = 0
        while start < N:
            k -= 1
            z = -ZETAS[k]
            for j in range(start, start + length):
                t = p[j]
                p[j] = t + p[j + length]
                p[j + length] = montgomery_reduce(z * (t - p[j + length]))
            start += 2 * length
        length <<= 1
    return [montgomery_reduce(F * x) for x in p]

def schoolbook_negacyclic(a, b):
    r = [0] * N
    for i in range(N):
        for j in range(N):
            k = i + j
            v = a[i] * b[j] % Q
            if k >= N:
                r[k - N] = (r[k - N] - v) % Q
            else:
                r[k] = (r[k] + v) % Q
    return [smod(x) for x in r]

def ring_product_standard(a, b):
    na, nb = ntt(a[:]), ntt(b[:])
    pw = [montgomery_reduce(na[i] * nb[i]) for i in range(N)]
    return [smod(x) for x in invntt_tomont(pw[:])]

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CORPUS = os.path.join(HERE, "tools", "vectors", "mldsa_ntt.json")

def gen():
    def poly(seed):
        random.seed(seed)
        return [random.randrange(Q) for _ in range(N)]
    vecs = []
    for seed, name in [(1001, "ntt: pseudorandom poly (seed 1001)"),
                       (1002, "ntt: pseudorandom poly (seed 1002)"),
                       (1003, "ntt: pseudorandom poly (seed 1003)")]:
        p = poly(seed)
        vecs.append({"type": "ntt", "name": name, "in": p, "ntt_out": ntt(p[:])})
    # explicit small-support cases (delta and constant) — sharp on twiddle bugs
    delta = [0] * N; delta[0] = 1
    vecs.append({"type": "ntt", "name": "ntt: delta (a=X^0)", "in": delta, "ntt_out": ntt(delta[:])})
    const = [1] * N
    vecs.append({"type": "ntt", "name": "ntt: all-ones", "in": const, "ntt_out": ntt(const[:])})
    for sa, sb, name in [(2001, 2002, "product: two pseudorandom polys"),
                         (2003, 2004, "product: two pseudorandom polys (2)")]:
        a, b = poly(sa), poly(sb)
        vecs.append({"type": "product", "name": name, "a": a, "b": b,
                     "prod": ring_product_standard(a, b)})
    doc = {"primitive": "mldsa_ntt",
           "source": "from-scratch FIPS 204 / Dilithium negacyclic NTT (zeta=1753, "
                     "q=8380417) generated by tools/verify_mldsa_vectors.py; ntt_out "
                     "is the exact int32 reference output, prod cross-checked by "
                     "O(n^2) schoolbook negacyclic convolution",
           "vectors": vecs}
    with open(CORPUS, "w") as f:
        json.dump(doc, f, indent=1)
    print("emitted %d vectors -> %s" % (len(vecs), CORPUS))

def verify():
    with open(CORPUS) as f:
        doc = json.load(f)
    n = ok = 0
    for v in doc["vectors"]:
        n += 1
        if v["type"] == "ntt":
            got = ntt(v["in"][:])
            if got != v["ntt_out"]:
                print("  bad: %s: fast-NTT recompute != ntt_out" % v["name"]); continue
            # second oracle: constant term of ntt(delta) etc. is implicitly covered
            ok += 1
        elif v["type"] == "product":
            fast = ring_product_standard(v["a"], v["b"])
            slow = schoolbook_negacyclic(v["a"], v["b"])
            if fast != slow:
                print("  bad: %s: fast ring-product != schoolbook oracle" % v["name"]); continue
            if [smod(x) for x in v["prod"]] != slow:
                print("  bad: %s: stored prod != schoolbook oracle" % v["name"]); continue
            ok += 1
        else:
            print("  bad: %s: unknown vector type %r" % (v.get("name"), v["type"]))
    print("mldsa ntt vectors: %d/%d OK" % (ok, n))
    return ok == n and n > 0

if __name__ == "__main__":
    # self-check the transform before touching the corpus
    random.seed(7)
    for _ in range(20):
        a = [random.randrange(Q) for _ in range(N)]
        assert [smod(x) for x in invntt_tomont(ntt(a[:]))] == [smod(a[i] * MONT) for i in range(N)], \
            "round-trip invntt_tomont(ntt(a)) != a*MONT"
    assert QINV == 58728449 and ZETAS[1] == 25847 and F == 41978, "constant drift"
    if "--emit" in sys.argv or not os.path.exists(CORPUS):
        gen()
    sys.exit(0 if verify() else 1)
