/* Determ C99-native BLAKE2b (RFC 7693).
 *
 * A fast cryptographic hash with keyed (MAC) and variable-length-output modes.
 * Vendored libsodium-free as the prerequisite for the Argon2id password-hash
 * (CRYPTO-C99-SPEC §3.6): Argon2's compression and its variable-length H' are
 * built on BLAKE2b. Also independently usable wherever libsodium's
 * `crypto_generichash` (which IS BLAKE2b) is wanted without the dependency.
 *
 * Validated by `determ test-blake2b-c99`: (1) the unkeyed 64-byte digest is
 * byte-equal vs OpenSSL `EVP_blake2b512` over a fuzzed message-length grid (the
 * §Q9 cross-validation gate — the full compression / G / SIGMA / IV / finalize
 * path); (2) keyed + variable-length outputs match reference vectors generated by
 * Python's `hashlib.blake2b` (an independent BLAKE2 implementation — OpenSSL's EVP
 * exposes only the unkeyed 64-byte digest); (3) incremental update == one-shot.
 *
 * No secret-dependent control flow or memory index (a hash/MAC over public-shaped
 * control flow); key material in the context is zeroized by determ_blake2b_final.
 */
#ifndef DETERM_CRYPTO_BLAKE2B_H
#define DETERM_CRYPTO_BLAKE2B_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DETERM_BLAKE2B_BLOCKBYTES 128u
#define DETERM_BLAKE2B_OUTBYTES   64u
#define DETERM_BLAKE2B_KEYBYTES   64u

typedef struct {
    uint64_t h[8];
    uint64_t t[2];
    uint64_t f[2];
    uint8_t  buf[DETERM_BLAKE2B_BLOCKBYTES];
    size_t   buflen;
    size_t   outlen;
} determ_blake2b_ctx;

/* Initialize for a digest of `outlen` bytes (1..64) with an optional key
 * (`key`/`keylen`, keylen 0..64; pass NULL/0 for an unkeyed hash). Returns 0 on
 * success, -1 if outlen is 0 or > 64, or keylen > 64. */
int  determ_blake2b_init(determ_blake2b_ctx *ctx, size_t outlen,
                         const uint8_t *key, size_t keylen);

/* Absorb `inlen` bytes. */
void determ_blake2b_update(determ_blake2b_ctx *ctx, const uint8_t *in, size_t inlen);

/* Emit the `outlen`-byte digest fixed at init and zeroize the context. */
void determ_blake2b_final(determ_blake2b_ctx *ctx, uint8_t *out);

/* One-shot: out[outlen] = BLAKE2b_keyed(key[keylen], in[inlen]). Returns 0 on
 * success, -1 on the same parameter errors as determ_blake2b_init. */
int  determ_blake2b(uint8_t *out, size_t outlen,
                    const uint8_t *key, size_t keylen,
                    const uint8_t *in, size_t inlen);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* DETERM_CRYPTO_BLAKE2B_H */
